// Auto-generated by BoltFFI. Do not edit.
package org.astarte.device.sdk.bindings;

/**
 * Discriminated union of all Astarte data types that can be sent or received over the FFI bridge.
 *
 * <p>Each concrete variant is a {@code public static final} inner class. Use {@code instanceof}
 * or a chain of {@code if} checks to distinguish variants at runtime:
 *
 * <pre>{@code
 * if (val instanceof AstarteVal.Double) {
 *     double v = ((AstarteVal.Double) val).value;
 * } else if (val instanceof AstarteVal.Integer) {
 *     int v = ((AstarteVal.Integer) val).value;
 * }
 * }</pre>
 *
 * <p>Variants mirror the Rust {@code AstarteData} type. {@code BinaryBlobArray} is intentionally
 * absent because nested {@code Vec<Vec<u8>>} cannot be expressed in the BoltFFI wire format.
 */
public abstract class AstarteVal {
    private AstarteVal() {}

    /** A 64-bit floating-point value. NaN and infinity are rejected by the Rust layer. */
    public static final class Double extends AstarteVal {
        public final double value;

        public Double(double value) {
            this.value = value;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) return true;
            if (!(obj instanceof Double)) return false;
            Double other = (Double) obj;
            return java.lang.Double.compare(this.value, other.value) == 0;
        }

        @Override
        public int hashCode() {
            int result = 1;
            result = 31 * result + java.lang.Double.hashCode(value);
            return result;
        }

        @Override
        public String toString() {
            return "AstarteVal.Double{" +
                "value=" + value +
                '}';
        }
    }

    /** A 32-bit signed integer. */
    public static final class Integer extends AstarteVal {
        public final int value;

        public Integer(int value) {
            this.value = value;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) return true;
            if (!(obj instanceof Integer)) return false;
            Integer other = (Integer) obj;
            return this.value == other.value;
        }

        @Override
        public int hashCode() {
            int result = 1;
            result = 31 * result + java.lang.Integer.hashCode(value);
            return result;
        }

        @Override
        public String toString() {
            return "AstarteVal.Integer{" +
                "value=" + value +
                '}';
        }
    }

    /** A boolean value. Named {@code Boolean} to mirror the Rust type; use {@code instanceof AstarteVal.Boolean} to check. */
    public static final class Boolean extends AstarteVal {
        public final boolean value;

        public Boolean(boolean value) {
            this.value = value;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) return true;
            if (!(obj instanceof Boolean)) return false;
            Boolean other = (Boolean) obj;
            return this.value == other.value;
        }

        @Override
        public int hashCode() {
            int result = 1;
            result = 31 * result + java.lang.Boolean.hashCode(value);
            return result;
        }

        @Override
        public String toString() {
            return "AstarteVal.Boolean{" +
                "value=" + value +
                '}';
        }
    }

    /** A 64-bit signed integer. */
    public static final class LongInteger extends AstarteVal {
        public final long value;

        public LongInteger(long value) {
            this.value = value;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) return true;
            if (!(obj instanceof LongInteger)) return false;
            LongInteger other = (LongInteger) obj;
            return this.value == other.value;
        }

        @Override
        public int hashCode() {
            int result = 1;
            result = 31 * result + Long.hashCode(value);
            return result;
        }

        @Override
        public String toString() {
            return "AstarteVal.LongInteger{" +
                "value=" + value +
                '}';
        }
    }

    /** A UTF-8 string. Named {@code IString} to avoid clashing with {@link String}. */
    public static final class IString extends AstarteVal {
        public final String value;

        public IString(String value) {
            this.value = value;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) return true;
            if (!(obj instanceof IString)) return false;
            IString other = (IString) obj;
            return java.util.Objects.equals(this.value, other.value);
        }

        @Override
        public int hashCode() {
            int result = 1;
            result = 31 * result + java.util.Objects.hashCode(value);
            return result;
        }

        @Override
        public String toString() {
            return "AstarteVal.IString{" +
                "value=" + value +
                '}';
        }
    }

    /** An arbitrary binary payload. */
    public static final class BinaryBlob extends AstarteVal {
        public final byte[] value;

        public BinaryBlob(byte[] value) {
            this.value = value;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) return true;
            if (!(obj instanceof BinaryBlob)) return false;
            BinaryBlob other = (BinaryBlob) obj;
            return java.util.Arrays.equals(this.value, other.value);
        }

        @Override
        public int hashCode() {
            int result = 1;
            result = 31 * result + java.util.Arrays.hashCode(value);
            return result;
        }

        @Override
        public String toString() {
            return "AstarteVal.BinaryBlob{" +
                "value=" + value +
                '}';
        }
    }

    /** A timestamp expressed as milliseconds since the Unix epoch (UTC). */
    public static final class DateTime extends AstarteVal {
        public final long value;

        public DateTime(long value) {
            this.value = value;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) return true;
            if (!(obj instanceof DateTime)) return false;
            DateTime other = (DateTime) obj;
            return this.value == other.value;
        }

        @Override
        public int hashCode() {
            int result = 1;
            result = 31 * result + Long.hashCode(value);
            return result;
        }

        @Override
        public String toString() {
            return "AstarteVal.DateTime{" +
                "value=" + value +
                '}';
        }
    }

    /** An array of 64-bit floats. Each element is validated (no NaN or infinity) by the Rust layer. */
    public static final class DoubleArray extends AstarteVal {
        public final double[] value;

        public DoubleArray(double[] value) {
            this.value = value;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) return true;
            if (!(obj instanceof DoubleArray)) return false;
            DoubleArray other = (DoubleArray) obj;
            return java.util.Arrays.equals(this.value, other.value);
        }

        @Override
        public int hashCode() {
            int result = 1;
            result = 31 * result + java.util.Arrays.hashCode(value);
            return result;
        }

        @Override
        public String toString() {
            return "AstarteVal.DoubleArray{" +
                "value=" + value +
                '}';
        }
    }

    /** An array of 32-bit signed integers. */
    public static final class IntegerArray extends AstarteVal {
        public final int[] value;

        public IntegerArray(int[] value) {
            this.value = value;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) return true;
            if (!(obj instanceof IntegerArray)) return false;
            IntegerArray other = (IntegerArray) obj;
            return java.util.Arrays.equals(this.value, other.value);
        }

        @Override
        public int hashCode() {
            int result = 1;
            result = 31 * result + java.util.Arrays.hashCode(value);
            return result;
        }

        @Override
        public String toString() {
            return "AstarteVal.IntegerArray{" +
                "value=" + value +
                '}';
        }
    }

    /** An array of boolean values. */
    public static final class BooleanArray extends AstarteVal {
        public final boolean[] value;

        public BooleanArray(boolean[] value) {
            this.value = value;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) return true;
            if (!(obj instanceof BooleanArray)) return false;
            BooleanArray other = (BooleanArray) obj;
            return java.util.Arrays.equals(this.value, other.value);
        }

        @Override
        public int hashCode() {
            int result = 1;
            result = 31 * result + java.util.Arrays.hashCode(value);
            return result;
        }

        @Override
        public String toString() {
            return "AstarteVal.BooleanArray{" +
                "value=" + value +
                '}';
        }
    }

    /** An array of 64-bit signed integers. */
    public static final class LongIntegerArray extends AstarteVal {
        public final long[] value;

        public LongIntegerArray(long[] value) {
            this.value = value;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) return true;
            if (!(obj instanceof LongIntegerArray)) return false;
            LongIntegerArray other = (LongIntegerArray) obj;
            return java.util.Arrays.equals(this.value, other.value);
        }

        @Override
        public int hashCode() {
            int result = 1;
            result = 31 * result + java.util.Arrays.hashCode(value);
            return result;
        }

        @Override
        public String toString() {
            return "AstarteVal.LongIntegerArray{" +
                "value=" + value +
                '}';
        }
    }

    /** An array of UTF-8 strings, exposed as an unmodifiable {@link java.util.List}. */
    public static final class StringArray extends AstarteVal {
        public final java.util.List<String> value;

        public StringArray(java.util.List<String> value) {
            this.value = value;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) return true;
            if (!(obj instanceof StringArray)) return false;
            StringArray other = (StringArray) obj;
            return WireWriter.listEquals(this.value, other.value, (leftItem0, rightItem0) -> java.util.Objects.equals(leftItem0, rightItem0));
        }

        @Override
        public int hashCode() {
            int result = 1;
            result = 31 * result + WireWriter.listHash(value, item0 -> java.util.Objects.hashCode(item0));
            return result;
        }

        @Override
        public String toString() {
            return "AstarteVal.StringArray{" +
                "value=" + value +
                '}';
        }
    }

    /** An array of timestamps, each expressed as milliseconds since the Unix epoch (UTC). */
    public static final class DateTimeArray extends AstarteVal {
        public final long[] value;

        public DateTimeArray(long[] value) {
            this.value = value;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) return true;
            if (!(obj instanceof DateTimeArray)) return false;
            DateTimeArray other = (DateTimeArray) obj;
            return java.util.Arrays.equals(this.value, other.value);
        }

        @Override
        public int hashCode() {
            int result = 1;
            result = 31 * result + java.util.Arrays.hashCode(value);
            return result;
        }

        @Override
        public String toString() {
            return "AstarteVal.DateTimeArray{" +
                "value=" + value +
                '}';
        }
    }

    static AstarteVal decode(WireReader reader) {
        int tag = reader.readI32();
        switch (tag) {
            case 0: return new Double(
                reader.readF64()
            );
            case 1: return new Integer(
                reader.readI32()
            );
            case 2: return new Boolean(
                reader.readBool()
            );
            case 3: return new LongInteger(
                reader.readI64()
            );
            case 4: return new IString(
                reader.readString()
            );
            case 5: return new BinaryBlob(
                reader.readByteArray()
            );
            case 6: return new DateTime(
                reader.readI64()
            );
            case 7: return new DoubleArray(
                reader.readDoubleArray()
            );
            case 8: return new IntegerArray(
                reader.readIntArray()
            );
            case 9: return new BooleanArray(
                reader.readBooleanArray()
            );
            case 10: return new LongIntegerArray(
                reader.readLongArray()
            );
            case 11: return new StringArray(
                reader.readList(readIndex0 -> reader.readString())
            );
            case 12: return new DateTimeArray(
                reader.readLongArray()
            );
            default: throw new RuntimeException("Unknown AstarteVal tag: " + tag);
        }
    }

    int wireEncodedSize() {
        if (this instanceof Double) {
            Double _v = (Double) this;
            return 4 + 8;
        }
        if (this instanceof Integer) {
            Integer _v = (Integer) this;
            return 4 + 4;
        }
        if (this instanceof Boolean) {
            Boolean _v = (Boolean) this;
            return 4 + 1;
        }
        if (this instanceof LongInteger) {
            LongInteger _v = (LongInteger) this;
            return 4 + 8;
        }
        if (this instanceof IString) {
            IString _v = (IString) this;
            return 4 + (4 + (4 + (_v.value).length() * 3));
        }
        if (this instanceof BinaryBlob) {
            BinaryBlob _v = (BinaryBlob) this;
            return 4 + (4 + _v.value.length);
        }
        if (this instanceof DateTime) {
            DateTime _v = (DateTime) this;
            return 4 + 8;
        }
        if (this instanceof DoubleArray) {
            DoubleArray _v = (DoubleArray) this;
            return 4 + (4 + WireWriter.vecLength(_v.value) * 8);
        }
        if (this instanceof IntegerArray) {
            IntegerArray _v = (IntegerArray) this;
            return 4 + (4 + WireWriter.vecLength(_v.value) * 4);
        }
        if (this instanceof BooleanArray) {
            BooleanArray _v = (BooleanArray) this;
            return 4 + (4 + WireWriter.vecLength(_v.value) * 1);
        }
        if (this instanceof LongIntegerArray) {
            LongIntegerArray _v = (LongIntegerArray) this;
            return 4 + (4 + WireWriter.vecLength(_v.value) * 8);
        }
        if (this instanceof StringArray) {
            StringArray _v = (StringArray) this;
            return 4 + WireWriter.listWireSize(_v.value, sizeItem0 -> (4 + (4 + (sizeItem0).length() * 3)));
        }
        if (this instanceof DateTimeArray) {
            DateTimeArray _v = (DateTimeArray) this;
            return 4 + (4 + WireWriter.vecLength(_v.value) * 8);
        }
        throw new RuntimeException("Unknown AstarteVal subtype");
    }

    void wireEncodeTo(WireWriter wire) {
        if (this instanceof Double) {
            Double _v = (Double) this;
            wire.writeI32(0);
            wire.writeF64(_v.value);
            return;
        }
        if (this instanceof Integer) {
            Integer _v = (Integer) this;
            wire.writeI32(1);
            wire.writeI32(_v.value);
            return;
        }
        if (this instanceof Boolean) {
            Boolean _v = (Boolean) this;
            wire.writeI32(2);
            wire.writeBool(_v.value);
            return;
        }
        if (this instanceof LongInteger) {
            LongInteger _v = (LongInteger) this;
            wire.writeI32(3);
            wire.writeI64(_v.value);
            return;
        }
        if (this instanceof IString) {
            IString _v = (IString) this;
            wire.writeI32(4);
            wire.writeString(_v.value);
            return;
        }
        if (this instanceof BinaryBlob) {
            BinaryBlob _v = (BinaryBlob) this;
            wire.writeI32(5);
            wire.writeByteArray(_v.value);
            return;
        }
        if (this instanceof DateTime) {
            DateTime _v = (DateTime) this;
            wire.writeI32(6);
            wire.writeI64(_v.value);
            return;
        }
        if (this instanceof DoubleArray) {
            DoubleArray _v = (DoubleArray) this;
            wire.writeI32(7);
            wire.writeDoubleArray(_v.value);
            return;
        }
        if (this instanceof IntegerArray) {
            IntegerArray _v = (IntegerArray) this;
            wire.writeI32(8);
            wire.writeIntArray(_v.value);
            return;
        }
        if (this instanceof BooleanArray) {
            BooleanArray _v = (BooleanArray) this;
            wire.writeI32(9);
            wire.writeBooleanArray(_v.value);
            return;
        }
        if (this instanceof LongIntegerArray) {
            LongIntegerArray _v = (LongIntegerArray) this;
            wire.writeI32(10);
            wire.writeLongArray(_v.value);
            return;
        }
        if (this instanceof StringArray) {
            StringArray _v = (StringArray) this;
            wire.writeI32(11);
            wire.writeI32(_v.value.size()); for (String item0 : _v.value) { wire.writeString(item0); };
            return;
        }
        if (this instanceof DateTimeArray) {
            DateTimeArray _v = (DateTimeArray) this;
            wire.writeI32(12);
            wire.writeLongArray(_v.value);
            return;
        }
        throw new RuntimeException("Unknown AstarteVal subtype");
    }
}