// Auto-generated by BoltFFI. Do not edit.
package org.astarte.device.sdk.bindings;

public abstract class AstarteVal {
    private AstarteVal() {}

    public static final class IInteger extends AstarteVal {
        public final int value;

        public IInteger(int value) {
            this.value = value;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) return true;
            if (!(obj instanceof IInteger)) return false;
            IInteger other = (IInteger) obj;
            return this.value == other.value;
        }

        @Override
        public int hashCode() {
            int result = 1;
            result = 31 * result + Integer.hashCode(value);
            return result;
        }

        @Override
        public String toString() {
            return "AstarteVal.IInteger{" +
                "value=" + value +
                '}';
        }
    }

    static AstarteVal decode(WireReader reader) {
        int tag = reader.readI32();
        switch (tag) {
            case 0: return new IInteger(
                reader.readI32()
            );
            default: throw new RuntimeException("Unknown AstarteVal tag: " + tag);
        }
    }

    int wireEncodedSize() {
        if (this instanceof IInteger) {
            IInteger _v = (IInteger) this;
            return 4 + 4;
        }
        throw new RuntimeException("Unknown AstarteVal subtype");
    }

    void wireEncodeTo(WireWriter wire) {
        if (this instanceof IInteger) {
            IInteger _v = (IInteger) this;
            wire.writeI32(0);
            wire.writeI32(_v.value);
            return;
        }
        throw new RuntimeException("Unknown AstarteVal subtype");
    }
}