// Auto-generated by BoltFFI. Do not edit.
package org.astarte.device.sdk.bindings;

import java.util.Objects;

/**
 * MQTT credentials and endpoint configuration required to connect a device to Astarte.
 *
 * <p>All fields are immutable. Obtain a pairing URL and credentials secret from the Astarte
 * dashboard or provisioning API before constructing this object.
 */
public final class AstarteConfig {
    /** Astarte realm the device belongs to. */
    public final String realm;
    /** Unique device identifier (base64url-encoded 128-bit value). */
    public final String deviceId;
    /** Device credential secret obtained during the pairing phase. */
    public final String credentialsSecret;
    /** Base URL of the Astarte Pairing API (e.g. {@code "https://api.astarte.example/pairing"}). */
    public final String pairingUrl;
    /** When {@code true}, TLS certificate validation is skipped. Use only in development. */
    public final boolean ignoreSsl;

    /**
     * @param realm             Astarte realm name
     * @param deviceId          device identifier (base64url, 128-bit)
     * @param credentialsSecret credential secret from the pairing phase
     * @param pairingUrl        base URL of the Astarte Pairing API
     * @param ignoreSsl         {@code true} to disable TLS certificate validation (dev only)
     */
    public AstarteConfig(String realm, String deviceId, String credentialsSecret, String pairingUrl, boolean ignoreSsl) {
        this.realm = realm;
        this.deviceId = deviceId;
        this.credentialsSecret = credentialsSecret;
        this.pairingUrl = pairingUrl;
        this.ignoreSsl = ignoreSsl;
    }

    public String realm() {
        return realm;
    }

    public String deviceId() {
        return deviceId;
    }

    public String credentialsSecret() {
        return credentialsSecret;
    }

    public String pairingUrl() {
        return pairingUrl;
    }

    public boolean ignoreSsl() {
        return ignoreSsl;
    }

    static AstarteConfig decode(WireReader reader) {
        return new AstarteConfig(
            reader.readString(),
            reader.readString(),
            reader.readString(),
            reader.readString(),
            reader.readBool()
        );
    }

    int wireEncodedSize() {
        return (4 + (4 + (realm).length() * 3)) + (4 + (4 + (deviceId).length() * 3)) + (4 + (4 + (credentialsSecret).length() * 3)) + (4 + (4 + (pairingUrl).length() * 3)) + 1;
    }

    void wireEncodeTo(WireWriter wire) {
        wire.writeString(realm);
        wire.writeString(deviceId);
        wire.writeString(credentialsSecret);
        wire.writeString(pairingUrl);
        wire.writeBool(ignoreSsl);
    }

    byte[] wireEncodeToBytes() {
        try (WireWriter wire = new WireWriter(wireEncodedSize())) {
            wireEncodeTo(wire);
            return wire.toByteArray();
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        AstarteConfig other = (AstarteConfig) obj;
        return java.util.Objects.equals(this.realm, other.realm) && java.util.Objects.equals(this.deviceId, other.deviceId) && java.util.Objects.equals(this.credentialsSecret, other.credentialsSecret) && java.util.Objects.equals(this.pairingUrl, other.pairingUrl) && this.ignoreSsl == other.ignoreSsl;
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + java.util.Objects.hashCode(realm);
        result = 31 * result + java.util.Objects.hashCode(deviceId);
        result = 31 * result + java.util.Objects.hashCode(credentialsSecret);
        result = 31 * result + java.util.Objects.hashCode(pairingUrl);
        result = 31 * result + Boolean.hashCode(ignoreSsl);
        return result;
    }

    @Override
    public String toString() {
        return "AstarteConfig{" +
            "realm=" + realm +
            ", deviceId=" + deviceId +
            ", credentialsSecret=" + credentialsSecret +
            ", pairingUrl=" + pairingUrl +
            ", ignoreSsl=" + ignoreSsl +
            '}';
    }
}