// Auto-generated by BoltFFI. Do not edit.
package org.astarte.device.sdk.bindings;

import java.util.Objects;

/**
 * A single named field within an Object-aggregation datastream event.
 *
 * <p>When {@link EventListener#onObjectReceived} is called, the payload is a list of
 * {@code ObjectEntry} items — one per mapped field in the Astarte interface. The {@link #key}
 * is the field name (last segment of the endpoint path) and {@link #value} is the field data
 * converted to the appropriate {@link AstarteVal} variant.
 */
public final class ObjectEntry {
    /** Field name as defined in the Astarte interface mapping. */
    public final String key;
    /** Field value, wrapped in the appropriate {@link AstarteVal} variant. */
    public final AstarteVal value;

    /**
     * @param key   field name
     * @param value field value
     */
    public ObjectEntry(String key, AstarteVal value) {
        this.key = key;
        this.value = value;
    }

    public String key() {
        return key;
    }

    public AstarteVal value() {
        return value;
    }

    static ObjectEntry decode(WireReader reader) {
        return new ObjectEntry(
            reader.readString(),
            AstarteVal.decode(reader)
        );
    }

    int wireEncodedSize() {
        return (4 + (4 + (key).length() * 3)) + value.wireEncodedSize();
    }

    void wireEncodeTo(WireWriter wire) {
        wire.writeString(key);
        value.wireEncodeTo(wire);
    }

    byte[] wireEncodeToBytes() {
        try (WireWriter wire = new WireWriter(wireEncodedSize())) {
            wireEncodeTo(wire);
            return wire.toByteArray();
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        ObjectEntry other = (ObjectEntry) obj;
        return java.util.Objects.equals(this.key, other.key) && java.util.Objects.equals(this.value, other.value);
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + java.util.Objects.hashCode(key);
        result = 31 * result + java.util.Objects.hashCode(value);
        return result;
    }

    @Override
    public String toString() {
        return "ObjectEntry{" +
            "key=" + key +
            ", value=" + value +
            '}';
    }
}