// Auto-generated by BoltFFI. Do not edit.
package org.astarte.device.sdk.bindings;

public enum SdkError {
    CONFIG,
    CONNECTION,
    SEND;

    private static final SdkError[] VARIANTS = values();

    static SdkError fromTag(int tag) {
        return VARIANTS[tag];
    }

    int wireTag() {
        return ordinal();
    }

    public static final class Exception extends RuntimeException {
        private final SdkError error;

        Exception(SdkError error) {
            super(error.name());
            this.error = error;
        }

        public SdkError getError() {
            return error;
        }
    }

    int nativeValue() {
        return ordinal();
    }
}