// Auto-generated by BoltFFI. Do not edit.
package org.astarte.device.sdk.bindings;

/**
 * Error categories surfaced by the Astarte Device SDK.
 *
 * <p>When a native method fails it throws {@link SdkError.Exception}. Inspect
 * {@link SdkError.Exception#getError()} to distinguish the failure category:
 *
 * <pre>{@code
 * try {
 *     device.send(iface, path, val);
 * } catch (SdkError.Exception e) {
 *     switch (e.getError()) {
 *         case CONFIG:     // bad configuration
 *         case CONNECTION: // broker unreachable or session lost
 *         case SEND:       // publish failed (invalid interface, path, or value)
 *     }
 * }
 * }</pre>
 */
public enum SdkError {
    /** The supplied {@link AstarteConfig} is invalid or the interface directory is missing. */
    CONFIG,
    /** The connection to the Astarte broker could not be established or was lost. */
    CONNECTION,
    /** A {@link AstarteDevice#send} call failed (e.g. invalid interface, path, or value). */
    SEND;

    private static final SdkError[] VARIANTS = values();

    static SdkError fromTag(int tag) {
        return VARIANTS[tag];
    }

    int wireTag() {
        return ordinal();
    }

    /**
     * Runtime exception wrapping an {@link SdkError} variant.
     *
     * <p>Thrown by {@link AstarteDevice} methods when the underlying Rust SDK returns an error.
     */
    public static final class Exception extends RuntimeException {
        private final SdkError error;

        Exception(SdkError error) {
            super(error.name());
            this.error = error;
        }

        /** Returns the SDK error category that caused this exception. */
        public SdkError getError() {
            return error;
        }
    }

    int nativeValue() {
        return ordinal();
    }
}