/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.example.list.LinkedList;

import static org.example.utilities.StringUtils.join;
import static org.example.utilities.StringUtils.split;
import static org.example.app.MessageUtils.getMessage;

import org.astarte.device.AstarteDevice;
import org.astarte.device.DeviceConfig;

public class App {
    public static void main(String[] args) {
        AstarteDevice device = new AstarteDevice();
        DeviceConfig config = new DeviceConfig.Mqtt("OqwCWJw8S5ei62ZPcxTzWw", "HqoCdyt8JCbEvhK75w7IKYd+ghhVDHhvBpDK6uUWIG8=", "test", "http://api.astarte.localhost/pairing", "examples/interfaces", "/tmp/bindings-test", 10);

        device.connect(config).join();

        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(result);
    }
}
