// Generated by jextract

package org.astarte.device.internal.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct NativeDeviceConfig {
 *     struct NativeConnectionConfig connection;
 *     struct NativeGenericDeviceConfig generic;
 * }
 * }
 */
public class NativeDeviceConfig {

    NativeDeviceConfig() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        NativeConnectionConfig.layout().withName("connection"),
        NativeGenericDeviceConfig.layout().withName("generic")
    ).withName("NativeDeviceConfig");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout connection$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("connection"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct NativeConnectionConfig connection
     * }
     */
    public static final GroupLayout connection$layout() {
        return connection$LAYOUT;
    }

    private static final long connection$OFFSET = $LAYOUT.byteOffset(groupElement("connection"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct NativeConnectionConfig connection
     * }
     */
    public static final long connection$offset() {
        return connection$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct NativeConnectionConfig connection
     * }
     */
    public static MemorySegment connection(MemorySegment struct) {
        return struct.asSlice(connection$OFFSET, connection$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct NativeConnectionConfig connection
     * }
     */
    public static void connection(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, connection$OFFSET, connection$LAYOUT.byteSize());
    }

    private static final GroupLayout generic$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("generic"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct NativeGenericDeviceConfig generic
     * }
     */
    public static final GroupLayout generic$layout() {
        return generic$LAYOUT;
    }

    private static final long generic$OFFSET = $LAYOUT.byteOffset(groupElement("generic"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct NativeGenericDeviceConfig generic
     * }
     */
    public static final long generic$offset() {
        return generic$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct NativeGenericDeviceConfig generic
     * }
     */
    public static MemorySegment generic(MemorySegment struct) {
        return struct.asSlice(generic$OFFSET, generic$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct NativeGenericDeviceConfig generic
     * }
     */
    public static void generic(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, generic$OFFSET, generic$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

