// Generated by jextract

package org.astarte.device.internal.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct NativeGenericDeviceConfig {
 *     const char *interfaces_dir;
 *     uintptr_t channel_size;
 *     const char *writable_dir;
 * }
 * }
 */
public class NativeGenericDeviceConfig {

    NativeGenericDeviceConfig() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        jextract_test_h.C_POINTER.withName("interfaces_dir"),
        jextract_test_h.C_LONG.withName("channel_size"),
        jextract_test_h.C_POINTER.withName("writable_dir")
    ).withName("NativeGenericDeviceConfig");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout interfaces_dir$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("interfaces_dir"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *interfaces_dir
     * }
     */
    public static final AddressLayout interfaces_dir$layout() {
        return interfaces_dir$LAYOUT;
    }

    private static final long interfaces_dir$OFFSET = $LAYOUT.byteOffset(groupElement("interfaces_dir"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *interfaces_dir
     * }
     */
    public static final long interfaces_dir$offset() {
        return interfaces_dir$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *interfaces_dir
     * }
     */
    public static MemorySegment interfaces_dir(MemorySegment struct) {
        return struct.get(interfaces_dir$LAYOUT, interfaces_dir$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *interfaces_dir
     * }
     */
    public static void interfaces_dir(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(interfaces_dir$LAYOUT, interfaces_dir$OFFSET, fieldValue);
    }

    private static final OfLong channel_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("channel_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uintptr_t channel_size
     * }
     */
    public static final OfLong channel_size$layout() {
        return channel_size$LAYOUT;
    }

    private static final long channel_size$OFFSET = $LAYOUT.byteOffset(groupElement("channel_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uintptr_t channel_size
     * }
     */
    public static final long channel_size$offset() {
        return channel_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uintptr_t channel_size
     * }
     */
    public static long channel_size(MemorySegment struct) {
        return struct.get(channel_size$LAYOUT, channel_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uintptr_t channel_size
     * }
     */
    public static void channel_size(MemorySegment struct, long fieldValue) {
        struct.set(channel_size$LAYOUT, channel_size$OFFSET, fieldValue);
    }

    private static final AddressLayout writable_dir$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("writable_dir"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *writable_dir
     * }
     */
    public static final AddressLayout writable_dir$layout() {
        return writable_dir$LAYOUT;
    }

    private static final long writable_dir$OFFSET = $LAYOUT.byteOffset(groupElement("writable_dir"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *writable_dir
     * }
     */
    public static final long writable_dir$offset() {
        return writable_dir$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *writable_dir
     * }
     */
    public static MemorySegment writable_dir(MemorySegment struct) {
        return struct.get(writable_dir$LAYOUT, writable_dir$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *writable_dir
     * }
     */
    public static void writable_dir(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(writable_dir$LAYOUT, writable_dir$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

