// Generated by jextract

package org.astarte.device.internal.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct NativeDeviceEvent {
 *     const char *interface;
 *     const char *path;
 *     struct NativeValue data;
 * } NativeManuallyDrop_NativeDeviceEvent
 * }
 */
public class NativeManuallyDrop_NativeDeviceEvent extends NativeDeviceEvent {

    NativeManuallyDrop_NativeDeviceEvent() {
        // Should not be called directly
    }
}

