// Generated by jextract

package org.astarte.device.internal.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct NativeDeviceData {
 *     NativeDeviceData_Tag tag;
 *     union {
 *         double double_;
 *         int32_t integer;
 *         _Bool boolean;
 *         int64_t long_integer;
 *         const char *string;
 *         struct CArray_u8 binary_blob;
 *         NativeTimestamp date_time;
 *         struct CArray_f64 double_array;
 *         struct CArray_i32 integer_array;
 *         struct CArray_bool boolean_array;
 *         struct CArray_i64 long_integer_array;
 *         struct CStringArray string_array;
 *         struct CArray_CArray_u8 binary_blob_array;
 *         struct CArray_NativeTimestamp date_time_array;
 *     } value;
 * }
 * }
 */
public class NativeDeviceData {

    NativeDeviceData() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        jextract_test_h.C_INT.withName("tag"),
        MemoryLayout.paddingLayout(4),
        NativeDeviceData.union (unnamed at ./jextract_test.h:129:3).layout().withName("value")
    ).withName("NativeDeviceData");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt tag$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * NativeDeviceData_Tag tag
     * }
     */
    public static final OfInt tag$layout() {
        return tag$LAYOUT;
    }

    private static final long tag$OFFSET = $LAYOUT.byteOffset(groupElement("tag"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * NativeDeviceData_Tag tag
     * }
     */
    public static final long tag$offset() {
        return tag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * NativeDeviceData_Tag tag
     * }
     */
    public static int tag(MemorySegment struct) {
        return struct.get(tag$LAYOUT, tag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * NativeDeviceData_Tag tag
     * }
     */
    public static void tag(MemorySegment struct, int fieldValue) {
        struct.set(tag$LAYOUT, tag$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * union {
     *     double double_;
     *     int32_t integer;
     *     _Bool boolean;
     *     int64_t long_integer;
     *     const char *string;
     *     struct CArray_u8 binary_blob;
     *     NativeTimestamp date_time;
     *     struct CArray_f64 double_array;
     *     struct CArray_i32 integer_array;
     *     struct CArray_bool boolean_array;
     *     struct CArray_i64 long_integer_array;
     *     struct CStringArray string_array;
     *     struct CArray_CArray_u8 binary_blob_array;
     *     struct CArray_NativeTimestamp date_time_array;
     * }
     * }
     */
    public static class union (unnamed at ./jextract_test.h:129:3) {

        union (unnamed at ./jextract_test.h:129:3)() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
            jextract_test_h.C_DOUBLE.withName("double_"),
            jextract_test_h.C_INT.withName("integer"),
            jextract_test_h.C_BOOL.withName("boolean"),
            jextract_test_h.C_LONG.withName("long_integer"),
            jextract_test_h.C_POINTER.withName("string"),
            CArray_u8.layout().withName("binary_blob"),
            jextract_test_h.C_LONG.withName("date_time"),
            CArray_f64.layout().withName("double_array"),
            CArray_i32.layout().withName("integer_array"),
            CArray_bool.layout().withName("boolean_array"),
            CArray_i64.layout().withName("long_integer_array"),
            CStringArray.layout().withName("string_array"),
            CArray_CArray_u8.layout().withName("binary_blob_array"),
            CArray_NativeTimestamp.layout().withName("date_time_array")
        ).withName("union (unnamed at ./jextract_test.h:129:3)");

        /**
         * The layout of this union
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        private static final OfDouble double_$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("double_"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * double double_
         * }
         */
        public static final OfDouble double_$layout() {
            return double_$LAYOUT;
        }

        private static final long double_$OFFSET = $LAYOUT.byteOffset(groupElement("double_"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * double double_
         * }
         */
        public static final long double_$offset() {
            return double_$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * double double_
         * }
         */
        public static double double_(MemorySegment union) {
            return union.get(double_$LAYOUT, double_$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * double double_
         * }
         */
        public static void double_(MemorySegment union, double fieldValue) {
            union.set(double_$LAYOUT, double_$OFFSET, fieldValue);
        }

        private static final OfInt integer$LAYOUT = (OfInt)$LAYOUT.select(groupElement("integer"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * int32_t integer
         * }
         */
        public static final OfInt integer$layout() {
            return integer$LAYOUT;
        }

        private static final long integer$OFFSET = $LAYOUT.byteOffset(groupElement("integer"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * int32_t integer
         * }
         */
        public static final long integer$offset() {
            return integer$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * int32_t integer
         * }
         */
        public static int integer(MemorySegment union) {
            return union.get(integer$LAYOUT, integer$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * int32_t integer
         * }
         */
        public static void integer(MemorySegment union, int fieldValue) {
            union.set(integer$LAYOUT, integer$OFFSET, fieldValue);
        }

        private static final OfBoolean boolean_$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("boolean"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * _Bool boolean
         * }
         */
        public static final OfBoolean boolean_$layout() {
            return boolean_$LAYOUT;
        }

        private static final long boolean_$OFFSET = $LAYOUT.byteOffset(groupElement("boolean"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * _Bool boolean
         * }
         */
        public static final long boolean_$offset() {
            return boolean_$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * _Bool boolean
         * }
         */
        public static boolean boolean_(MemorySegment union) {
            return union.get(boolean_$LAYOUT, boolean_$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * _Bool boolean
         * }
         */
        public static void boolean_(MemorySegment union, boolean fieldValue) {
            union.set(boolean_$LAYOUT, boolean_$OFFSET, fieldValue);
        }

        private static final OfLong long_integer$LAYOUT = (OfLong)$LAYOUT.select(groupElement("long_integer"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * int64_t long_integer
         * }
         */
        public static final OfLong long_integer$layout() {
            return long_integer$LAYOUT;
        }

        private static final long long_integer$OFFSET = $LAYOUT.byteOffset(groupElement("long_integer"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * int64_t long_integer
         * }
         */
        public static final long long_integer$offset() {
            return long_integer$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * int64_t long_integer
         * }
         */
        public static long long_integer(MemorySegment union) {
            return union.get(long_integer$LAYOUT, long_integer$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * int64_t long_integer
         * }
         */
        public static void long_integer(MemorySegment union, long fieldValue) {
            union.set(long_integer$LAYOUT, long_integer$OFFSET, fieldValue);
        }

        private static final AddressLayout string$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("string"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * const char *string
         * }
         */
        public static final AddressLayout string$layout() {
            return string$LAYOUT;
        }

        private static final long string$OFFSET = $LAYOUT.byteOffset(groupElement("string"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * const char *string
         * }
         */
        public static final long string$offset() {
            return string$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * const char *string
         * }
         */
        public static MemorySegment string(MemorySegment union) {
            return union.get(string$LAYOUT, string$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * const char *string
         * }
         */
        public static void string(MemorySegment union, MemorySegment fieldValue) {
            union.set(string$LAYOUT, string$OFFSET, fieldValue);
        }

        private static final GroupLayout binary_blob$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("binary_blob"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct CArray_u8 binary_blob
         * }
         */
        public static final GroupLayout binary_blob$layout() {
            return binary_blob$LAYOUT;
        }

        private static final long binary_blob$OFFSET = $LAYOUT.byteOffset(groupElement("binary_blob"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct CArray_u8 binary_blob
         * }
         */
        public static final long binary_blob$offset() {
            return binary_blob$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct CArray_u8 binary_blob
         * }
         */
        public static MemorySegment binary_blob(MemorySegment union) {
            return union.asSlice(binary_blob$OFFSET, binary_blob$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct CArray_u8 binary_blob
         * }
         */
        public static void binary_blob(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, binary_blob$OFFSET, binary_blob$LAYOUT.byteSize());
        }

        private static final OfLong date_time$LAYOUT = (OfLong)$LAYOUT.select(groupElement("date_time"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * NativeTimestamp date_time
         * }
         */
        public static final OfLong date_time$layout() {
            return date_time$LAYOUT;
        }

        private static final long date_time$OFFSET = $LAYOUT.byteOffset(groupElement("date_time"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * NativeTimestamp date_time
         * }
         */
        public static final long date_time$offset() {
            return date_time$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * NativeTimestamp date_time
         * }
         */
        public static long date_time(MemorySegment union) {
            return union.get(date_time$LAYOUT, date_time$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * NativeTimestamp date_time
         * }
         */
        public static void date_time(MemorySegment union, long fieldValue) {
            union.set(date_time$LAYOUT, date_time$OFFSET, fieldValue);
        }

        private static final GroupLayout double_array$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("double_array"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct CArray_f64 double_array
         * }
         */
        public static final GroupLayout double_array$layout() {
            return double_array$LAYOUT;
        }

        private static final long double_array$OFFSET = $LAYOUT.byteOffset(groupElement("double_array"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct CArray_f64 double_array
         * }
         */
        public static final long double_array$offset() {
            return double_array$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct CArray_f64 double_array
         * }
         */
        public static MemorySegment double_array(MemorySegment union) {
            return union.asSlice(double_array$OFFSET, double_array$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct CArray_f64 double_array
         * }
         */
        public static void double_array(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, double_array$OFFSET, double_array$LAYOUT.byteSize());
        }

        private static final GroupLayout integer_array$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("integer_array"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct CArray_i32 integer_array
         * }
         */
        public static final GroupLayout integer_array$layout() {
            return integer_array$LAYOUT;
        }

        private static final long integer_array$OFFSET = $LAYOUT.byteOffset(groupElement("integer_array"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct CArray_i32 integer_array
         * }
         */
        public static final long integer_array$offset() {
            return integer_array$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct CArray_i32 integer_array
         * }
         */
        public static MemorySegment integer_array(MemorySegment union) {
            return union.asSlice(integer_array$OFFSET, integer_array$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct CArray_i32 integer_array
         * }
         */
        public static void integer_array(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, integer_array$OFFSET, integer_array$LAYOUT.byteSize());
        }

        private static final GroupLayout boolean_array$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("boolean_array"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct CArray_bool boolean_array
         * }
         */
        public static final GroupLayout boolean_array$layout() {
            return boolean_array$LAYOUT;
        }

        private static final long boolean_array$OFFSET = $LAYOUT.byteOffset(groupElement("boolean_array"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct CArray_bool boolean_array
         * }
         */
        public static final long boolean_array$offset() {
            return boolean_array$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct CArray_bool boolean_array
         * }
         */
        public static MemorySegment boolean_array(MemorySegment union) {
            return union.asSlice(boolean_array$OFFSET, boolean_array$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct CArray_bool boolean_array
         * }
         */
        public static void boolean_array(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, boolean_array$OFFSET, boolean_array$LAYOUT.byteSize());
        }

        private static final GroupLayout long_integer_array$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("long_integer_array"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct CArray_i64 long_integer_array
         * }
         */
        public static final GroupLayout long_integer_array$layout() {
            return long_integer_array$LAYOUT;
        }

        private static final long long_integer_array$OFFSET = $LAYOUT.byteOffset(groupElement("long_integer_array"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct CArray_i64 long_integer_array
         * }
         */
        public static final long long_integer_array$offset() {
            return long_integer_array$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct CArray_i64 long_integer_array
         * }
         */
        public static MemorySegment long_integer_array(MemorySegment union) {
            return union.asSlice(long_integer_array$OFFSET, long_integer_array$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct CArray_i64 long_integer_array
         * }
         */
        public static void long_integer_array(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, long_integer_array$OFFSET, long_integer_array$LAYOUT.byteSize());
        }

        private static final GroupLayout string_array$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("string_array"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct CStringArray string_array
         * }
         */
        public static final GroupLayout string_array$layout() {
            return string_array$LAYOUT;
        }

        private static final long string_array$OFFSET = $LAYOUT.byteOffset(groupElement("string_array"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct CStringArray string_array
         * }
         */
        public static final long string_array$offset() {
            return string_array$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct CStringArray string_array
         * }
         */
        public static MemorySegment string_array(MemorySegment union) {
            return union.asSlice(string_array$OFFSET, string_array$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct CStringArray string_array
         * }
         */
        public static void string_array(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, string_array$OFFSET, string_array$LAYOUT.byteSize());
        }

        private static final GroupLayout binary_blob_array$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("binary_blob_array"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct CArray_CArray_u8 binary_blob_array
         * }
         */
        public static final GroupLayout binary_blob_array$layout() {
            return binary_blob_array$LAYOUT;
        }

        private static final long binary_blob_array$OFFSET = $LAYOUT.byteOffset(groupElement("binary_blob_array"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct CArray_CArray_u8 binary_blob_array
         * }
         */
        public static final long binary_blob_array$offset() {
            return binary_blob_array$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct CArray_CArray_u8 binary_blob_array
         * }
         */
        public static MemorySegment binary_blob_array(MemorySegment union) {
            return union.asSlice(binary_blob_array$OFFSET, binary_blob_array$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct CArray_CArray_u8 binary_blob_array
         * }
         */
        public static void binary_blob_array(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, binary_blob_array$OFFSET, binary_blob_array$LAYOUT.byteSize());
        }

        private static final GroupLayout date_time_array$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("date_time_array"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct CArray_NativeTimestamp date_time_array
         * }
         */
        public static final GroupLayout date_time_array$layout() {
            return date_time_array$LAYOUT;
        }

        private static final long date_time_array$OFFSET = $LAYOUT.byteOffset(groupElement("date_time_array"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct CArray_NativeTimestamp date_time_array
         * }
         */
        public static final long date_time_array$offset() {
            return date_time_array$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct CArray_NativeTimestamp date_time_array
         * }
         */
        public static MemorySegment date_time_array(MemorySegment union) {
            return union.asSlice(date_time_array$OFFSET, date_time_array$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct CArray_NativeTimestamp date_time_array
         * }
         */
        public static void date_time_array(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, date_time_array$OFFSET, date_time_array$LAYOUT.byteSize());
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this union
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout value$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union {
     *     double double_;
     *     int32_t integer;
     *     _Bool boolean;
     *     int64_t long_integer;
     *     const char *string;
     *     struct CArray_u8 binary_blob;
     *     NativeTimestamp date_time;
     *     struct CArray_f64 double_array;
     *     struct CArray_i32 integer_array;
     *     struct CArray_bool boolean_array;
     *     struct CArray_i64 long_integer_array;
     *     struct CStringArray string_array;
     *     struct CArray_CArray_u8 binary_blob_array;
     *     struct CArray_NativeTimestamp date_time_array;
     * } value
     * }
     */
    public static final GroupLayout value$layout() {
        return value$LAYOUT;
    }

    private static final long value$OFFSET = $LAYOUT.byteOffset(groupElement("value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union {
     *     double double_;
     *     int32_t integer;
     *     _Bool boolean;
     *     int64_t long_integer;
     *     const char *string;
     *     struct CArray_u8 binary_blob;
     *     NativeTimestamp date_time;
     *     struct CArray_f64 double_array;
     *     struct CArray_i32 integer_array;
     *     struct CArray_bool boolean_array;
     *     struct CArray_i64 long_integer_array;
     *     struct CStringArray string_array;
     *     struct CArray_CArray_u8 binary_blob_array;
     *     struct CArray_NativeTimestamp date_time_array;
     * } value
     * }
     */
    public static final long value$offset() {
        return value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union {
     *     double double_;
     *     int32_t integer;
     *     _Bool boolean;
     *     int64_t long_integer;
     *     const char *string;
     *     struct CArray_u8 binary_blob;
     *     NativeTimestamp date_time;
     *     struct CArray_f64 double_array;
     *     struct CArray_i32 integer_array;
     *     struct CArray_bool boolean_array;
     *     struct CArray_i64 long_integer_array;
     *     struct CStringArray string_array;
     *     struct CArray_CArray_u8 binary_blob_array;
     *     struct CArray_NativeTimestamp date_time_array;
     * } value
     * }
     */
    public static MemorySegment value(MemorySegment struct) {
        return struct.asSlice(value$OFFSET, value$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union {
     *     double double_;
     *     int32_t integer;
     *     _Bool boolean;
     *     int64_t long_integer;
     *     const char *string;
     *     struct CArray_u8 binary_blob;
     *     NativeTimestamp date_time;
     *     struct CArray_f64 double_array;
     *     struct CArray_i32 integer_array;
     *     struct CArray_bool boolean_array;
     *     struct CArray_i64 long_integer_array;
     *     struct CStringArray string_array;
     *     struct CArray_CArray_u8 binary_blob_array;
     *     struct CArray_NativeTimestamp date_time_array;
     * } value
     * }
     */
    public static void value(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, value$OFFSET, value$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

