// Generated by jextract

package org.astarte.device.internal.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct NativeGrpcConnectionConfig {
 *     const char *message_hub_addr;
 * }
 * }
 */
public class NativeGrpcConnectionConfig {

    NativeGrpcConnectionConfig() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        jextract_test_h.C_POINTER.withName("message_hub_addr")
    ).withName("NativeGrpcConnectionConfig");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout message_hub_addr$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("message_hub_addr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *message_hub_addr
     * }
     */
    public static final AddressLayout message_hub_addr$layout() {
        return message_hub_addr$LAYOUT;
    }

    private static final long message_hub_addr$OFFSET = $LAYOUT.byteOffset(groupElement("message_hub_addr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *message_hub_addr
     * }
     */
    public static final long message_hub_addr$offset() {
        return message_hub_addr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *message_hub_addr
     * }
     */
    public static MemorySegment message_hub_addr(MemorySegment struct) {
        return struct.get(message_hub_addr$LAYOUT, message_hub_addr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *message_hub_addr
     * }
     */
    public static void message_hub_addr(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(message_hub_addr$LAYOUT, message_hub_addr$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

