// Generated by jextract

package org.astarte.device.internal.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct NativeMqttConnectionConfig {
 *     const char *device_id;
 *     const char *cred_secr;
 *     const char *realm;
 *     const char *pairing_url;
 * }
 * }
 */
public class NativeMqttConnectionConfig {

    NativeMqttConnectionConfig() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        jextract_test_h.C_POINTER.withName("device_id"),
        jextract_test_h.C_POINTER.withName("cred_secr"),
        jextract_test_h.C_POINTER.withName("realm"),
        jextract_test_h.C_POINTER.withName("pairing_url")
    ).withName("NativeMqttConnectionConfig");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout device_id$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("device_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *device_id
     * }
     */
    public static final AddressLayout device_id$layout() {
        return device_id$LAYOUT;
    }

    private static final long device_id$OFFSET = $LAYOUT.byteOffset(groupElement("device_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *device_id
     * }
     */
    public static final long device_id$offset() {
        return device_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *device_id
     * }
     */
    public static MemorySegment device_id(MemorySegment struct) {
        return struct.get(device_id$LAYOUT, device_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *device_id
     * }
     */
    public static void device_id(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(device_id$LAYOUT, device_id$OFFSET, fieldValue);
    }

    private static final AddressLayout cred_secr$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cred_secr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *cred_secr
     * }
     */
    public static final AddressLayout cred_secr$layout() {
        return cred_secr$LAYOUT;
    }

    private static final long cred_secr$OFFSET = $LAYOUT.byteOffset(groupElement("cred_secr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *cred_secr
     * }
     */
    public static final long cred_secr$offset() {
        return cred_secr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *cred_secr
     * }
     */
    public static MemorySegment cred_secr(MemorySegment struct) {
        return struct.get(cred_secr$LAYOUT, cred_secr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *cred_secr
     * }
     */
    public static void cred_secr(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cred_secr$LAYOUT, cred_secr$OFFSET, fieldValue);
    }

    private static final AddressLayout realm$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("realm"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *realm
     * }
     */
    public static final AddressLayout realm$layout() {
        return realm$LAYOUT;
    }

    private static final long realm$OFFSET = $LAYOUT.byteOffset(groupElement("realm"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *realm
     * }
     */
    public static final long realm$offset() {
        return realm$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *realm
     * }
     */
    public static MemorySegment realm(MemorySegment struct) {
        return struct.get(realm$LAYOUT, realm$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *realm
     * }
     */
    public static void realm(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(realm$LAYOUT, realm$OFFSET, fieldValue);
    }

    private static final AddressLayout pairing_url$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pairing_url"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *pairing_url
     * }
     */
    public static final AddressLayout pairing_url$layout() {
        return pairing_url$LAYOUT;
    }

    private static final long pairing_url$OFFSET = $LAYOUT.byteOffset(groupElement("pairing_url"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *pairing_url
     * }
     */
    public static final long pairing_url$offset() {
        return pairing_url$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *pairing_url
     * }
     */
    public static MemorySegment pairing_url(MemorySegment struct) {
        return struct.get(pairing_url$LAYOUT, pairing_url$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *pairing_url
     * }
     */
    public static void pairing_url(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pairing_url$LAYOUT, pairing_url$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

