// Generated by jextract

package org.astarte.device.internal.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct NativeConnectionConfig {
 *     NativeConnectionConfig_Tag tag;
 *     union {
 *         struct NativeMqttConnectionConfig mqtt;
 *         struct NativeGrpcConnectionConfig grpc;
 *     } value;
 * }
 * }
 */
public class NativeConnectionConfig {

    NativeConnectionConfig() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        jextract_test_h.C_INT.withName("tag"),
        MemoryLayout.paddingLayout(4),
        NativeConnectionConfig.union (unnamed at ./jextract_test.h:28:3).layout().withName("value")
    ).withName("NativeConnectionConfig");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt tag$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * NativeConnectionConfig_Tag tag
     * }
     */
    public static final OfInt tag$layout() {
        return tag$LAYOUT;
    }

    private static final long tag$OFFSET = $LAYOUT.byteOffset(groupElement("tag"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * NativeConnectionConfig_Tag tag
     * }
     */
    public static final long tag$offset() {
        return tag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * NativeConnectionConfig_Tag tag
     * }
     */
    public static int tag(MemorySegment struct) {
        return struct.get(tag$LAYOUT, tag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * NativeConnectionConfig_Tag tag
     * }
     */
    public static void tag(MemorySegment struct, int fieldValue) {
        struct.set(tag$LAYOUT, tag$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * union {
     *     struct NativeMqttConnectionConfig mqtt;
     *     struct NativeGrpcConnectionConfig grpc;
     * }
     * }
     */
    public static class union (unnamed at ./jextract_test.h:28:3) {

        union (unnamed at ./jextract_test.h:28:3)() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
            NativeMqttConnectionConfig.layout().withName("mqtt"),
            NativeGrpcConnectionConfig.layout().withName("grpc")
        ).withName("union (unnamed at ./jextract_test.h:28:3)");

        /**
         * The layout of this union
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        private static final GroupLayout mqtt$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("mqtt"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct NativeMqttConnectionConfig mqtt
         * }
         */
        public static final GroupLayout mqtt$layout() {
            return mqtt$LAYOUT;
        }

        private static final long mqtt$OFFSET = $LAYOUT.byteOffset(groupElement("mqtt"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct NativeMqttConnectionConfig mqtt
         * }
         */
        public static final long mqtt$offset() {
            return mqtt$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct NativeMqttConnectionConfig mqtt
         * }
         */
        public static MemorySegment mqtt(MemorySegment union) {
            return union.asSlice(mqtt$OFFSET, mqtt$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct NativeMqttConnectionConfig mqtt
         * }
         */
        public static void mqtt(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, mqtt$OFFSET, mqtt$LAYOUT.byteSize());
        }

        private static final GroupLayout grpc$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("grpc"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct NativeGrpcConnectionConfig grpc
         * }
         */
        public static final GroupLayout grpc$layout() {
            return grpc$LAYOUT;
        }

        private static final long grpc$OFFSET = $LAYOUT.byteOffset(groupElement("grpc"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct NativeGrpcConnectionConfig grpc
         * }
         */
        public static final long grpc$offset() {
            return grpc$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct NativeGrpcConnectionConfig grpc
         * }
         */
        public static MemorySegment grpc(MemorySegment union) {
            return union.asSlice(grpc$OFFSET, grpc$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct NativeGrpcConnectionConfig grpc
         * }
         */
        public static void grpc(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, grpc$OFFSET, grpc$LAYOUT.byteSize());
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this union
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout value$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union {
     *     struct NativeMqttConnectionConfig mqtt;
     *     struct NativeGrpcConnectionConfig grpc;
     * } value
     * }
     */
    public static final GroupLayout value$layout() {
        return value$LAYOUT;
    }

    private static final long value$OFFSET = $LAYOUT.byteOffset(groupElement("value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union {
     *     struct NativeMqttConnectionConfig mqtt;
     *     struct NativeGrpcConnectionConfig grpc;
     * } value
     * }
     */
    public static final long value$offset() {
        return value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union {
     *     struct NativeMqttConnectionConfig mqtt;
     *     struct NativeGrpcConnectionConfig grpc;
     * } value
     * }
     */
    public static MemorySegment value(MemorySegment struct) {
        return struct.asSlice(value$OFFSET, value$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union {
     *     struct NativeMqttConnectionConfig mqtt;
     *     struct NativeGrpcConnectionConfig grpc;
     * } value
     * }
     */
    public static void value(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, value$OFFSET, value$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

