// Generated by jextract

package org.astarte.device.internal.jextract;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct NativeStringResult_bool {
 *     NativeStringResult_bool_Tag tag;
 *     union {
 *         _Bool ok;
 *         StaticString err;
 *     } value;
 * }
 * }
 */
public class NativeStringResult_bool {

    NativeStringResult_bool() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        jextract_test_h.C_INT.withName("tag"),
        MemoryLayout.paddingLayout(4),
        NativeStringResult_bool.union (unnamed at ./jextract_test.h:54:3).layout().withName("value")
    ).withName("NativeStringResult_bool");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt tag$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * NativeStringResult_bool_Tag tag
     * }
     */
    public static final OfInt tag$layout() {
        return tag$LAYOUT;
    }

    private static final long tag$OFFSET = $LAYOUT.byteOffset(groupElement("tag"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * NativeStringResult_bool_Tag tag
     * }
     */
    public static final long tag$offset() {
        return tag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * NativeStringResult_bool_Tag tag
     * }
     */
    public static int tag(MemorySegment struct) {
        return struct.get(tag$LAYOUT, tag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * NativeStringResult_bool_Tag tag
     * }
     */
    public static void tag(MemorySegment struct, int fieldValue) {
        struct.set(tag$LAYOUT, tag$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * union {
     *     _Bool ok;
     *     StaticString err;
     * }
     * }
     */
    public static class union (unnamed at ./jextract_test.h:54:3) {

        union (unnamed at ./jextract_test.h:54:3)() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
            jextract_test_h.C_BOOL.withName("ok"),
            jextract_test_h.C_POINTER.withName("err")
        ).withName("union (unnamed at ./jextract_test.h:54:3)");

        /**
         * The layout of this union
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        private static final OfBoolean ok$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("ok"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * _Bool ok
         * }
         */
        public static final OfBoolean ok$layout() {
            return ok$LAYOUT;
        }

        private static final long ok$OFFSET = $LAYOUT.byteOffset(groupElement("ok"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * _Bool ok
         * }
         */
        public static final long ok$offset() {
            return ok$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * _Bool ok
         * }
         */
        public static boolean ok(MemorySegment union) {
            return union.get(ok$LAYOUT, ok$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * _Bool ok
         * }
         */
        public static void ok(MemorySegment union, boolean fieldValue) {
            union.set(ok$LAYOUT, ok$OFFSET, fieldValue);
        }

        private static final AddressLayout err$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("err"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * StaticString err
         * }
         */
        public static final AddressLayout err$layout() {
            return err$LAYOUT;
        }

        private static final long err$OFFSET = $LAYOUT.byteOffset(groupElement("err"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * StaticString err
         * }
         */
        public static final long err$offset() {
            return err$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * StaticString err
         * }
         */
        public static MemorySegment err(MemorySegment union) {
            return union.get(err$LAYOUT, err$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * StaticString err
         * }
         */
        public static void err(MemorySegment union, MemorySegment fieldValue) {
            union.set(err$LAYOUT, err$OFFSET, fieldValue);
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this union
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout value$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union {
     *     _Bool ok;
     *     StaticString err;
     * } value
     * }
     */
    public static final GroupLayout value$layout() {
        return value$LAYOUT;
    }

    private static final long value$OFFSET = $LAYOUT.byteOffset(groupElement("value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union {
     *     _Bool ok;
     *     StaticString err;
     * } value
     * }
     */
    public static final long value$offset() {
        return value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union {
     *     _Bool ok;
     *     StaticString err;
     * } value
     * }
     */
    public static MemorySegment value(MemorySegment struct) {
        return struct.asSlice(value$OFFSET, value$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union {
     *     _Bool ok;
     *     StaticString err;
     * } value
     * }
     */
    public static void value(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, value$OFFSET, value$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

