/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation(project(":astarte"))
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}

tasks.withType<JavaExec>().configureEach {
    jvmArgs("--enable-native-access=org.astarte.device")
}
