/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import org.apache.commons.text.WordUtils;
import org.astarte.device.sdk.bindings.AstarteConfig;
import org.astarte.device.sdk.bindings.AstarteDevice;
import org.astarte.device.sdk.bindings.AstarteVal;
import org.astarte.device.sdk.bindings.EventListener;
import static org.example.app.MessageUtils.getMessage;
import org.example.list.LinkedList;
import static org.example.utilities.StringUtils.join;
import static org.example.utilities.StringUtils.split;

public class App {

    public static void main(String[] args) throws InterruptedException {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));

        AstarteConfig astarteConfig = new AstarteConfig("test", "Pm9iVIl6SUSW4YpSnIArdw", "2eZm3TBy1q++QYGCdnEZ3quyH265D+rnrFBt88HamOw=", "http://api.astarte.localhost/pairing", true);
        try (AstarteDevice device = new AstarteDevice(astarteConfig, "../../interfaces")) {
            ExecutorService executor = Executors.newSingleThreadExecutor();
            executor.submit(() -> {
                device.startListening(new EventListener() {
                    @Override
                    public void onConnected() {
                        System.err.println("Unimplemented method 'onConnected'");
                    }

                    @Override
                    public void onDisconnected() {
                        System.err.println("Unimplemented method 'onDisconnected'");
                    }

                    @Override
                    public void onDataReceived(String _interface, String path, AstarteVal data) {
                        System.err.println("Unimplemented method 'onDataReceived'");
                    }
                });
            });
            int i = 0;
            while (i < 10) {
                device.send("com.example.MyInterface", "/my/path", new AstarteVal.IInteger(10));
                i++;
                Thread.sleep(1000);
            }

            device.disconenct();
            device.close();
        }
    }
}
