// Auto-generated by BoltFFI. Do not edit.
@file:Suppress("unused", "RedundantVisibilityModifier", "MemberVisibilityCanBePrivate", "PropertyName", "FunctionName", "ClassName", "LocalVariableName", "SpellCheckingInspection", "NOTHING_TO_INLINE", "KotlinRedundantDiagnosticSuppress")

package org.astarte.device.sdk.bindings

import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicLong
import kotlin.coroutines.Continuation
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
import kotlinx.coroutines.CancellableContinuation
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.jvm.JvmInline
import java.time.Duration
import java.time.Instant
import java.util.UUID
import java.net.URI

class FfiException(val code: Int, message: String) : Exception(message)

private fun takeLastErrorMessage(): String =
    Native.boltffi_last_error_message().toString(Charsets.UTF_8)

object BoltFFIScope : CoroutineScope {
    override val coroutineContext = Dispatchers.Default + SupervisorJob()

    fun launchOnMain(block: suspend CoroutineScope.() -> Unit): Job =
        launch(Dispatchers.Default, block = block)
}

class BoltFFIException(val errorBuffer: ByteBuffer) : Exception("Structured error") {
    init {
        errorBuffer.order(ByteOrder.nativeOrder())
    }
}

private inline fun <T> useWireBytes(bytes: ByteArray, block: (java.nio.ByteBuffer) -> T): T {
    return block(java.nio.ByteBuffer.wrap(bytes).order(java.nio.ByteOrder.LITTLE_ENDIAN))
}



private const val BOLTFFI_FUTURE_POLL_READY: Byte = 0
private const val BOLTFFI_FUTURE_POLL_WAKE: Byte = 1

internal class BoltFFIHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = AtomicLong(1)

    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(2)
        map[handle] = obj
        return handle
    }

    fun remove(handle: Long): T =
        map.remove(handle) ?: throw IllegalStateException("BoltFFIHandleMap: invalid handle $handle")

    fun tryRemove(handle: Long): T? = map.remove(handle)

    fun get(handle: Long): T =
        map[handle] ?: throw IllegalStateException("BoltFFIHandleMap: invalid handle $handle")
}

private val boltffiContinuationMap = BoltFFIHandleMap<CancellableContinuation<Byte>>()

internal suspend inline fun <T> boltffiCallAsync(
    crossinline createFuture: () -> Long,
    crossinline poll: (Long, Long) -> Unit,
    crossinline complete: (Long) -> T,
    crossinline free: (Long) -> Unit,
    crossinline cancel: (Long) -> Unit
): T {
    val rustFuture = createFuture()
    try {
        var pollResult: Byte
        do {
            pollResult = suspendCancellableCoroutine<Byte> { continuation ->
                continuation.invokeOnCancellation { cancel(rustFuture) }
                poll(rustFuture, boltffiContinuationMap.insert(continuation))
            }
        } while (pollResult != BOLTFFI_FUTURE_POLL_READY)
        return complete(rustFuture)
    } finally {
        free(rustFuture)
    }
}

interface WireCodable {
    fun encode(writer: WireWriter)

    interface Decoder<T> {
        fun decode(reader: WireReader): T
    }
}

class WireReader {
    private val array: ByteArray?
    private val buffer: ByteBuffer?
    private var pos: Int = 0

    constructor(array: ByteArray) {
        this.array = array
        this.buffer = null
    }

    constructor(buffer: ByteBuffer) {
        this.array = null
        this.buffer = buffer.slice().order(ByteOrder.LITTLE_ENDIAN)
    }

    private fun byteAt(index: Int): Byte = array?.get(index) ?: buffer!!.get(index)

    private fun copyRange(start: Int, len: Int): ByteArray {
        val localArray = array
        if (localArray != null) {
            return localArray.copyOfRange(start, start + len)
        }
        val bytes = ByteArray(len)
        if (len == 0) return bytes
        val source = buffer!!.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        source.position(start)
        source.limit(start + len)
        source.get(bytes)
        return bytes
    }

    @PublishedApi internal fun leI16(o: Int): Short {
        val localArray = array
        return if (localArray != null) {
            ((localArray[o].toInt() and 0xFF) or ((localArray[o + 1].toInt() and 0xFF) shl 8)).toShort()
        } else {
            buffer!!.getShort(o)
        }
    }

    @PublishedApi internal fun leI32(o: Int): Int {
        val localArray = array
        return if (localArray != null) {
            (localArray[o].toInt() and 0xFF) or
            ((localArray[o + 1].toInt() and 0xFF) shl 8) or
            ((localArray[o + 2].toInt() and 0xFF) shl 16) or
            ((localArray[o + 3].toInt() and 0xFF) shl 24)
        } else {
            buffer!!.getInt(o)
        }
    }

    @PublishedApi internal fun leI64(o: Int): Long {
        val localArray = array
        return if (localArray != null) {
            (localArray[o].toLong() and 0xFFL) or
            ((localArray[o + 1].toLong() and 0xFFL) shl 8) or
            ((localArray[o + 2].toLong() and 0xFFL) shl 16) or
            ((localArray[o + 3].toLong() and 0xFFL) shl 24) or
            ((localArray[o + 4].toLong() and 0xFFL) shl 32) or
            ((localArray[o + 5].toLong() and 0xFFL) shl 40) or
            ((localArray[o + 6].toLong() and 0xFFL) shl 48) or
            ((localArray[o + 7].toLong() and 0xFFL) shl 56)
        } else {
            buffer!!.getLong(o)
        }
    }

    fun readBool(): Boolean { val v = byteAt(pos) != 0.toByte(); pos += 1; return v }
    fun readI8(): Byte { val v = byteAt(pos); pos += 1; return v }
    fun readU8(): UByte { val v = byteAt(pos).toUByte(); pos += 1; return v }
    fun readI16(): Short { val v = leI16(pos); pos += 2; return v }
    fun readU16(): UShort { val v = leI16(pos).toUShort(); pos += 2; return v }
    fun readI32(): Int { val v = leI32(pos); pos += 4; return v }
    fun readU32(): UInt { val v = leI32(pos).toUInt(); pos += 4; return v }
    fun readI64(): Long { val v = leI64(pos); pos += 8; return v }
    fun readU64(): ULong { val v = leI64(pos).toULong(); pos += 8; return v }
    fun readF32(): Float { val v = Float.fromBits(leI32(pos)); pos += 4; return v }
    fun readF64(): Double { val v = Double.fromBits(leI64(pos)); pos += 8; return v }

    fun readString(): String {
        val len = leI32(pos).toUInt().toInt()
        pos += 4
        if (len == 0) return ""
        val start = pos
        pos += len
        val localArray = array
        return if (localArray != null) {
            String(localArray, start, len, Charsets.UTF_8)
        } else {
            String(copyRange(start, len), Charsets.UTF_8)
        }
    }

    fun readBytes(): ByteArray {
        val len = leI32(pos).toUInt().toInt()
        pos += 4
        if (len == 0) return ByteArray(0)
        val start = pos
        pos += len
        return copyRange(start, len)
    }

    fun readDuration(): Duration {
        val seconds = readI64()
        val nanos = readI32().toLong()
        require(seconds >= 0L) { "Duration out of range" }
        require(nanos >= 0L) { "Duration nanos out of range" }
        return Duration.ofSeconds(seconds, nanos)
    }

    fun readInstant(): Instant {
        val seconds = readI64()
        val nanos = readI32().toLong()
        require(nanos >= 0L) { "Instant nanos out of range" }
        if (seconds >= 0L) {
            return Instant.EPOCH.plus(Duration.ofSeconds(seconds, nanos))
        }
        require(seconds != Long.MIN_VALUE) { "Instant out of range" }
        return Instant.EPOCH.minus(Duration.ofSeconds(-seconds, nanos))
    }

    fun readUuid(): UUID = UUID(readI64(), readI64())

    fun readUri(): URI = URI.create(readString())

    inline fun <T> readOptional(reader: (WireReader) -> T): T? {
        val tag = readU8().toInt()
        return if (tag == 0) null else reader(this)
    }

    inline fun <T> readList(reader: (WireReader) -> T): List<T> {
        val count = readI32().toUInt().toInt()
        if (count == 0) return emptyList()
        return ArrayList<T>(count).also { list -> repeat(count) { list.add(reader(this)) } }
    }

    inline fun <T, E> readResult(okReader: (WireReader) -> T, errReader: (WireReader) -> E): BoltFFIResult<T, E> {
        val tag = readU8().toInt()
        return if (tag == 0) BoltFFIResult.Ok(okReader(this)) else BoltFFIResult.Err(errReader(this))
    }

    fun readShortArray(): ShortArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return ShortArray(0)
        val base = pos
        pos += count * 2
        val localArray = array
        return if (localArray != null) {
            ShortArray(count) { i -> leI16(base + i * 2) }
        } else {
            val localBuffer = buffer!!
            ShortArray(count) { i -> localBuffer.getShort(base + i * 2) }
        }
    }

    fun readIntArray(): IntArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return IntArray(0)
        val base = pos
        pos += count * 4
        val localArray = array
        return if (localArray != null) {
            IntArray(count) { i -> leI32(base + i * 4) }
        } else {
            val localBuffer = buffer!!
            IntArray(count) { i -> localBuffer.getInt(base + i * 4) }
        }
    }

    fun readLongArray(): LongArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return LongArray(0)
        val base = pos
        pos += count * 8
        val localArray = array
        return if (localArray != null) {
            LongArray(count) { i -> leI64(base + i * 8) }
        } else {
            val localBuffer = buffer!!
            LongArray(count) { i -> localBuffer.getLong(base + i * 8) }
        }
    }

    fun readFloatArray(): FloatArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return FloatArray(0)
        val base = pos
        pos += count * 4
        val localArray = array
        return if (localArray != null) {
            FloatArray(count) { i -> Float.fromBits(leI32(base + i * 4)) }
        } else {
            val localBuffer = buffer!!
            FloatArray(count) { i -> localBuffer.getFloat(base + i * 4) }
        }
    }

    fun readDoubleArray(): DoubleArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return DoubleArray(0)
        val base = pos
        pos += count * 8
        val localArray = array
        return if (localArray != null) {
            DoubleArray(count) { i -> Double.fromBits(leI64(base + i * 8)) }
        } else {
            val localBuffer = buffer!!
            DoubleArray(count) { i -> localBuffer.getDouble(base + i * 8) }
        }
    }

    fun readBooleanArray(): BooleanArray {
        val count = readI32().toUInt().toInt()
        if (count == 0) return BooleanArray(0)
        val base = pos
        pos += count
        val localArray = array
        return if (localArray != null) {
            BooleanArray(count) { i -> localArray[base + i] != 0.toByte() }
        } else {
            val localBuffer = buffer!!
            BooleanArray(count) { i -> localBuffer.get(base + i) != 0.toByte() }
        }
    }

    fun skip(count: Int) { pos += count }

    fun readBlittable(sizeBytes: Int): ByteArray {
        val start = pos
        pos += sizeBytes
        return copyRange(start, sizeBytes)
    }
}

sealed class BoltFFIResult<out T, out E> {
    data class Ok<T>(val value: T) : BoltFFIResult<T, Nothing>()
    data class Err<E>(val error: E) : BoltFFIResult<Nothing, E>()

    val isSuccess: Boolean get() = this is Ok
    val isFailure: Boolean get() = this is Err

    fun getOrThrow(): T = when (this) {
        is Ok -> value
        is Err -> throw when (error) {
            is Throwable -> error
            else -> FfiException(-1, error.toString())
        }
    }

    fun getOrNull(): T? = when (this) {
        is Ok -> value
        is Err -> null
    }

    fun exceptionOrNull(): Throwable? = when (this) {
        is Ok -> null
        is Err -> when (error) {
            is Throwable -> error
            else -> FfiException(-1, error.toString())
        }
    }

    inline fun <R> fold(onSuccess: (T) -> R, onFailure: (E) -> R): R = when (this) {
        is Ok -> onSuccess(value)
        is Err -> onFailure(error)
    }
}

@Suppress("UNCHECKED_CAST")
internal fun <T> boltffiUnsafeCast(value: Any?): T = value as T

private object Utf8Codec {
    fun maxBytes(value: String): Int = value.length * 3
}

class WireWriter(initialCapacity: Int = 256) {
    private var buffer: ByteBuffer = ByteBuffer.allocateDirect(initialCapacity).order(ByteOrder.LITTLE_ENDIAN)
    private var pos: Int = 0

    internal fun reset(requiredCapacity: Int) {
        if (buffer.capacity() < requiredCapacity) {
            buffer = ByteBuffer.allocateDirect(requiredCapacity).order(ByteOrder.LITTLE_ENDIAN)
        }
        pos = 0
    }

    internal fun asDirectBuffer(): ByteBuffer {
        val view = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        view.limit(pos)
        view.position(0)
        return view.slice().order(ByteOrder.LITTLE_ENDIAN)
    }

    internal fun toByteArray(): ByteArray {
        val arr = ByteArray(pos)
        val view = buffer.duplicate()
        view.position(0)
        view.get(arr, 0, pos)
        return arr
    }

    private fun ensureCapacity(needed: Int) {
        val required = pos + needed
        if (required <= buffer.capacity()) return
        val nextCapacity = maxOf(buffer.capacity() * 2, required)
        val next = ByteBuffer.allocateDirect(nextCapacity).order(ByteOrder.LITTLE_ENDIAN)
        val source = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        source.limit(pos)
        source.position(0)
        next.put(source)
        buffer = next
    }

    internal inline fun writeRawBytes(byteCount: Int, writer: (ByteBuffer, Int) -> Unit) {
        ensureCapacity(byteCount)
        val baseOffset = pos
        writer(buffer, baseOffset)
        pos = baseOffset + byteCount
    }

    fun writeBool(v: Boolean) { ensureCapacity(1); buffer.put(pos, if (v) 1 else 0); pos += 1 }
    fun writePadding(count: Int) {
        ensureCapacity(count)
        val view = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        view.position(pos)
        repeat(count) { view.put(0) }
        pos += count
    }
    fun writeI8(v: Byte) { ensureCapacity(1); buffer.put(pos, v); pos += 1 }
    fun writeU8(v: UByte) { ensureCapacity(1); buffer.put(pos, v.toByte()); pos += 1 }

    fun writeI16(v: Short) { ensureCapacity(2); buffer.putShort(pos, v); pos += 2 }
    fun writeU16(v: UShort) = writeI16(v.toShort())

    fun writeI32(v: Int) { ensureCapacity(4); buffer.putInt(pos, v); pos += 4 }
    fun writeU32(v: UInt) = writeI32(v.toInt())

    fun writeI64(v: Long) { ensureCapacity(8); buffer.putLong(pos, v); pos += 8 }
    fun writeU64(v: ULong) = writeI64(v.toLong())

    fun writeF32(v: Float) = writeI32(java.lang.Float.floatToRawIntBits(v))
    fun writeF64(v: Double) = writeI64(java.lang.Double.doubleToRawLongBits(v))

    fun writeDuration(v: Duration) {
        require(v.seconds >= 0L) { "Invalid duration, must be non-negative" }
        require(v.nano >= 0) { "Invalid duration nanos" }
        writeI64(v.seconds)
        writeI32(v.nano)
    }

    fun writeInstant(v: Instant) {
        var epochOffset = Duration.between(Instant.EPOCH, v)
        var sign = 1L
        if (epochOffset.isNegative) {
            sign = -1L
            epochOffset = epochOffset.negated()
        }
        require(epochOffset.nano >= 0) { "Invalid instant nanos" }
        writeI64(sign * epochOffset.seconds)
        writeI32(epochOffset.nano)
    }

    fun writeUuid(v: UUID) {
        writeI64(v.mostSignificantBits)
        writeI64(v.leastSignificantBits)
    }

    fun writeUri(v: URI) {
        writeString(v.toString())
    }

    fun writeString(v: String) {
        val bytes = v.toByteArray(Charsets.UTF_8)
        writeU32(bytes.size.toUInt())
        ensureCapacity(bytes.size)
        val view = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        view.position(pos)
        view.put(bytes)
        pos += bytes.size
    }

    fun writeBytes(v: ByteArray) {
        writeU32(v.size.toUInt())
        ensureCapacity(v.size)
        val view = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        view.position(pos)
        view.put(v)
        pos += v.size
    }

    fun writePrimitiveList(v: IntArray) {
        writeU32(v.size.toUInt())
        val bytes = v.size * 4
        writeRawBytes(bytes) { buf, baseOffset ->
            val view = buf.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            view.position(baseOffset)
            view.limit(baseOffset + bytes)
            view.slice().order(ByteOrder.LITTLE_ENDIAN).asIntBuffer().put(v)
        }
    }

    fun writePrimitiveList(v: LongArray) {
        writeU32(v.size.toUInt())
        val bytes = v.size * 8
        writeRawBytes(bytes) { buf, baseOffset ->
            val view = buf.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            view.position(baseOffset)
            view.limit(baseOffset + bytes)
            view.slice().order(ByteOrder.LITTLE_ENDIAN).asLongBuffer().put(v)
        }
    }

    fun writePrimitiveList(v: FloatArray) {
        writeU32(v.size.toUInt())
        val bytes = v.size * 4
        writeRawBytes(bytes) { buf, baseOffset ->
            val view = buf.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            view.position(baseOffset)
            view.limit(baseOffset + bytes)
            view.slice().order(ByteOrder.LITTLE_ENDIAN).asFloatBuffer().put(v)
        }
    }

    fun writePrimitiveList(v: DoubleArray) {
        writeU32(v.size.toUInt())
        val bytes = v.size * 8
        writeRawBytes(bytes) { buf, baseOffset ->
            val view = buf.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            view.position(baseOffset)
            view.limit(baseOffset + bytes)
            view.slice().order(ByteOrder.LITTLE_ENDIAN).asDoubleBuffer().put(v)
        }
    }

    fun writePrimitiveList(v: ShortArray) {
        writeU32(v.size.toUInt())
        val bytes = v.size * 2
        writeRawBytes(bytes) { buf, baseOffset ->
            val view = buf.duplicate().order(ByteOrder.LITTLE_ENDIAN)
            view.position(baseOffset)
            view.limit(baseOffset + bytes)
            view.slice().order(ByteOrder.LITTLE_ENDIAN).asShortBuffer().put(v)
        }
    }

    fun writePrimitiveList(v: ByteArray) {
        writeU32(v.size.toUInt())
        ensureCapacity(v.size)
        val view = buffer.duplicate().order(ByteOrder.LITTLE_ENDIAN)
        view.position(pos)
        view.put(v)
        pos += v.size
    }

    fun writePrimitiveList(v: BooleanArray) {
        writeU32(v.size.toUInt())
        v.forEach { writeBool(it) }
    }

    @JvmName("writeIntList")
    fun writePrimitiveList(v: List<Int>) {
        writeU32(v.size.toUInt())
        v.forEach { writeI32(it) }
    }

    @JvmName("writeLongList")
    fun writePrimitiveList(v: List<Long>) {
        writeU32(v.size.toUInt())
        v.forEach { writeI64(it) }
    }

    inline fun <reified T> writeBlittable(v: T) {
        when (v) {
            is Byte -> writeI8(v)
            is Short -> writeI16(v)
            is Int -> writeI32(v)
            is Long -> writeI64(v)
            is Float -> writeF32(v)
            is Double -> writeF64(v)
            is Boolean -> writeBool(v)
            else -> throw IllegalArgumentException("Cannot write blittable: ${T::class}")
        }
    }

    inline fun <reified T> writeBlittableList(v: List<T>) {
        writeU32(v.size.toUInt())
        v.forEach { item -> writeBlittable(item) }
    }
}

private const val MAX_CACHED_WIRE_WRITER_BYTES: Int = 1024 * 1024

internal class WireWriterPoolState(private val cacheSize: Int = 4) {
    private val cachedWriters: Array<WireWriter?> = arrayOfNulls(cacheSize)
    private var depth: Int = 0

    fun acquire(requiredCapacity: Int): BorrowedWireWriter {
        val slot = depth
        depth = slot + 1
        val shouldCache = requiredCapacity <= MAX_CACHED_WIRE_WRITER_BYTES && slot < cacheSize
        val writer = if (shouldCache) {
            cachedWriters[slot] ?: WireWriter(requiredCapacity).also { cachedWriters[slot] = it }
        } else {
            WireWriter(requiredCapacity)
        }

        writer.reset(requiredCapacity)
        return BorrowedWireWriter(this, writer)
    }

    fun release() {
        depth -= 1
    }
}

internal class BorrowedWireWriter(
    private val state: WireWriterPoolState,
    internal val writer: WireWriter
) : AutoCloseable {
    internal val buffer: ByteBuffer
        get() = writer.asDirectBuffer()

    override fun close() {
        state.release()
    }
}

internal object WireWriterPool {
    private val state: ThreadLocal<WireWriterPoolState> = ThreadLocal.withInitial { WireWriterPoolState() }

    fun acquire(requiredCapacity: Int): BorrowedWireWriter {
        val poolState = state.get() ?: WireWriterPoolState().also { state.set(it) }
        return poolState.acquire(requiredCapacity)
    }
}

sealed class AstarteVal {

    data class Double(val `value`: kotlin.Double) : AstarteVal()

    data class Integer(val `value`: Int) : AstarteVal()

    data class Boolean(val `value`: kotlin.Boolean) : AstarteVal()

    data class LongInteger(val `value`: Long) : AstarteVal()

    data class IString(val `value`: String) : AstarteVal()

    data class BinaryBlob(val `value`: ByteArray) : AstarteVal()

    data class DateTime(val `value`: Long) : AstarteVal()

    data class DoubleArray(val `value`: kotlin.DoubleArray) : AstarteVal()

    data class IntegerArray(val `value`: IntArray) : AstarteVal()

    data class BooleanArray(val `value`: kotlin.BooleanArray) : AstarteVal()

    data class LongIntegerArray(val `value`: LongArray) : AstarteVal()

    data class StringArray(val `value`: List<String>) : AstarteVal()

    data class DateTimeArray(val `value`: LongArray) : AstarteVal()

    companion object {
        fun decode(reader: WireReader): AstarteVal {
            val tag = reader.readI32()
            return when (tag) {
                0 -> {
                    Double(
                        reader.readF64()
                    )
                }
                1 -> {
                    Integer(
                        reader.readI32()
                    )
                }
                2 -> {
                    Boolean(
                        reader.readBool()
                    )
                }
                3 -> {
                    LongInteger(
                        reader.readI64()
                    )
                }
                4 -> {
                    IString(
                        reader.readString()
                    )
                }
                5 -> {
                    BinaryBlob(
                        reader.readBytes()
                    )
                }
                6 -> {
                    DateTime(
                        reader.readI64()
                    )
                }
                7 -> {
                    DoubleArray(
                        reader.readDoubleArray()
                    )
                }
                8 -> {
                    IntegerArray(
                        reader.readIntArray()
                    )
                }
                9 -> {
                    BooleanArray(
                        reader.readBooleanArray()
                    )
                }
                10 -> {
                    LongIntegerArray(
                        reader.readLongArray()
                    )
                }
                11 -> {
                    StringArray(
                        reader.readList { reader.readString() }
                    )
                }
                12 -> {
                    DateTimeArray(
                        reader.readLongArray()
                    )
                }
                else -> throw FfiException(-1, "Unknown AstarteVal tag: $tag")
            }
        }
    }

    fun wireEncodedSize(): Int = 4 + when (this) {
        is Double -> 8
        is Integer -> 4
        is Boolean -> 1
        is LongInteger -> 8
        is IString -> (4 + Utf8Codec.maxBytes(`value`))
        is BinaryBlob -> (4 + `value`.size)
        is DateTime -> 8
        is DoubleArray -> (4 + `value`.size * 8)
        is IntegerArray -> (4 + `value`.size * 4)
        is BooleanArray -> (4 + `value`.size * 1)
        is LongIntegerArray -> (4 + `value`.size * 8)
        is StringArray -> (4 + `value`.sumOf { item -> ((4 + Utf8Codec.maxBytes(item))).toInt() })
        is DateTimeArray -> (4 + `value`.size * 8)
    }

    fun wireEncodeTo(wire: WireWriter) {
        when (this) {
            is Double -> {
                wire.writeI32(0)
                wire.writeF64(`value`)
            }
            is Integer -> {
                wire.writeI32(1)
                wire.writeI32(`value`)
            }
            is Boolean -> {
                wire.writeI32(2)
                wire.writeBool(`value`)
            }
            is LongInteger -> {
                wire.writeI32(3)
                wire.writeI64(`value`)
            }
            is IString -> {
                wire.writeI32(4)
                wire.writeString(`value`)
            }
            is BinaryBlob -> {
                wire.writeI32(5)
                wire.writePrimitiveList(`value`)
            }
            is DateTime -> {
                wire.writeI32(6)
                wire.writeI64(`value`)
            }
            is DoubleArray -> {
                wire.writeI32(7)
                wire.writePrimitiveList(`value`)
            }
            is IntegerArray -> {
                wire.writeI32(8)
                wire.writePrimitiveList(`value`)
            }
            is BooleanArray -> {
                wire.writeI32(9)
                wire.writePrimitiveList(`value`)
            }
            is LongIntegerArray -> {
                wire.writeI32(10)
                wire.writePrimitiveList(`value`)
            }
            is StringArray -> {
                wire.writeI32(11)
                wire.writeU32(`value`.size.toUInt()); `value`.forEach { item -> wire.writeString(item) }
            }
            is DateTimeArray -> {
                wire.writeI32(12)
                wire.writePrimitiveList(`value`)
            }
        }
    }
}

sealed class SdkError : Exception() {

    data class Config(val msg: String) : SdkError()

    data class Connection(val msg: String) : SdkError()

    data class Send(val msg: String) : SdkError()

    companion object {
        fun decode(reader: WireReader): SdkError {
            val tag = reader.readI32()
            return when (tag) {
                0 -> {
                    Config(
                        reader.readString()
                    )
                }
                1 -> {
                    Connection(
                        reader.readString()
                    )
                }
                2 -> {
                    Send(
                        reader.readString()
                    )
                }
                else -> throw FfiException(-1, "Unknown SdkError tag: $tag")
            }
        }
    }

    fun wireEncodedSize(): Int = 4 + when (this) {
        is Config -> (4 + Utf8Codec.maxBytes(msg))
        is Connection -> (4 + Utf8Codec.maxBytes(msg))
        is Send -> (4 + Utf8Codec.maxBytes(msg))
    }

    fun wireEncodeTo(wire: WireWriter) {
        when (this) {
            is Config -> {
                wire.writeI32(0)
                wire.writeString(msg)
            }
            is Connection -> {
                wire.writeI32(1)
                wire.writeString(msg)
            }
            is Send -> {
                wire.writeI32(2)
                wire.writeString(msg)
            }
        }
    }
}

/**
 * One field of an Object-aggregation event (key + converted value).
 */
data class ObjectEntry(
    val key: String,
    val `value`: AstarteVal
) {
    companion object {
        fun decode(reader: WireReader): ObjectEntry = ObjectEntry(
            reader.readString(),
            AstarteVal.decode(reader)
        )
    }
    fun wireEncodedSize(): Int =
        (4 + Utf8Codec.maxBytes(key)) +
        `value`.wireEncodedSize()

    fun wireEncodeTo(wire: WireWriter) {
        wire.writeString(key)
        `value`.wireEncodeTo(wire)
    }
}

/**
 * Simplified configuration record.
 */
data class AstarteConfig(
    val realm: String,
    val deviceId: String,
    val credentialsSecret: String,
    val pairingUrl: String,
    val ignoreSsl: Boolean
) {
    companion object {
        fun decode(reader: WireReader): AstarteConfig = AstarteConfig(
            reader.readString(),
            reader.readString(),
            reader.readString(),
            reader.readString(),
            reader.readBool()
        )
    }
    fun wireEncodedSize(): Int =
        (4 + Utf8Codec.maxBytes(realm)) +
        (4 + Utf8Codec.maxBytes(deviceId)) +
        (4 + Utf8Codec.maxBytes(credentialsSecret)) +
        (4 + Utf8Codec.maxBytes(pairingUrl)) +
        1

    fun wireEncodeTo(wire: WireWriter) {
        wire.writeString(realm)
        wire.writeString(deviceId)
        wire.writeString(credentialsSecret)
        wire.writeString(pairingUrl)
        wire.writeBool(ignoreSsl)
    }
}

class AstarteDevice private constructor(internal val handle: Long) : AutoCloseable {
    private val closed = AtomicBoolean(false)

    constructor(config: AstarteConfig, interfacesDir: String) : this(
        kotlin.run {
            val wire_writer_config = WireWriterPool.acquire(config.wireEncodedSize())
        kotlin.run {
            val wire = wire_writer_config.writer
            config.wireEncodeTo(wire)
        }
            try {
                val handle = Native.boltffi_astarte_device_new(wire_writer_config.buffer, interfacesDir.toByteArray(Charsets.UTF_8))
                if (handle == 0L) throw FfiException(1, takeLastErrorMessage())
                handle
            } finally {
                wire_writer_config.close()
            }
        }
    )

    override fun close() {
        if (!closed.compareAndSet(false, true)) return
        Native.boltffi_astarte_device_free(handle)
    }


    fun send(interfaceName: String, interfacePath: String, `data`: AstarteVal) {
        val wire_writer_data = WireWriterPool.acquire(`data`.wireEncodedSize())
            run {
                val wire = wire_writer_data.writer
                `data`.wireEncodeTo(wire)
            }
        try {
            Native.boltffi_astarte_device_send(handle, interfaceName.toByteArray(Charsets.UTF_8), interfacePath.toByteArray(Charsets.UTF_8), wire_writer_data.buffer)
        } finally {
            wire_writer_data.close()
        }
    }


    fun startListening(listener: EventListener) {
        Native.boltffi_astarte_device_start_listening(handle, EventListenerBridge.create(listener))
    }


    fun disconenct() {
        Native.boltffi_astarte_device_disconenct(handle)
    }
}

/**
 * Foreign languages implement this trait to receive events.
 */
/**
 * ### Thread Safety
 *
 * Callback methods may be invoked from any thread and the thread is not guaranteed to be
 * the same between calls. **Your implementation must be thread-safe.**
 * Use `BoltFFIScope.launchOnMain` if updating UI.
 */
interface EventListener {
    fun onConnected()
    fun onDisconnected()
    /**
     * Called for Individual datastream events.
     */
    fun onDataReceived(`interface`: String, path: String, `data`: AstarteVal)
    /**
     * Called for Object (aggregate) datastream events. Unsupported fields are silently skipped.
     */
    fun onObjectReceived(`interface`: String, path: String, entries: List<ObjectEntry>)
    /**
     * Called when a property is set.
     */
    fun onPropertyReceived(`interface`: String, path: String, `data`: AstarteVal)
    /**
     * Called when a property is unset.
     */
    fun onPropertyUnset(`interface`: String, path: String)
}

private object EventListenerHandleMap {
    private val map = java.util.concurrent.ConcurrentHashMap<Long, EventListener>()
    private val counter = java.util.concurrent.atomic.AtomicLong(1L)

    fun insert(obj: EventListener): Long {
        val handle = counter.getAndAdd(2L)
        map[handle] = obj
        return handle
    }

    fun get(handle: Long): EventListener? = map[handle]

    fun remove(handle: Long): EventListener? = map.remove(handle)

    fun clone(handle: Long): Long {
        val obj = map[handle] ?: return 0L
        return insert(obj)
    }
}

object EventListenerCallbacks {
    @JvmStatic
    fun free(handle: Long) {
        EventListenerHandleMap.remove(handle)
    }

    @JvmStatic
    fun clone(handle: Long): Long {
        return EventListenerHandleMap.clone(handle)
    }

    @JvmStatic
    fun on_connected(handle: Long) {
        val impl = EventListenerHandleMap.get(handle) ?: error("EventListenerHandleMap: invalid handle $handle")
        impl.onConnected()
    }

    @JvmStatic
    fun on_disconnected(handle: Long) {
        val impl = EventListenerHandleMap.get(handle) ?: error("EventListenerHandleMap: invalid handle $handle")
        impl.onDisconnected()
    }

    @JvmStatic
    fun on_data_received(handle: Long, `interface`: ByteBuffer, path: ByteBuffer, `data`: ByteBuffer) {
        val impl = EventListenerHandleMap.get(handle) ?: error("EventListenerHandleMap: invalid handle $handle")
        impl.onDataReceived(run { val reader = WireReader(`interface`); reader.readString() }, run { val reader = WireReader(path); reader.readString() }, run { val reader = WireReader(`data`); AstarteVal.decode(reader) })
    }

    @JvmStatic
    fun on_object_received(handle: Long, `interface`: ByteBuffer, path: ByteBuffer, entries: ByteBuffer) {
        val impl = EventListenerHandleMap.get(handle) ?: error("EventListenerHandleMap: invalid handle $handle")
        impl.onObjectReceived(run { val reader = WireReader(`interface`); reader.readString() }, run { val reader = WireReader(path); reader.readString() }, run { val reader = WireReader(entries); reader.readList { ObjectEntry.decode(reader) } })
    }

    @JvmStatic
    fun on_property_received(handle: Long, `interface`: ByteBuffer, path: ByteBuffer, `data`: ByteBuffer) {
        val impl = EventListenerHandleMap.get(handle) ?: error("EventListenerHandleMap: invalid handle $handle")
        impl.onPropertyReceived(run { val reader = WireReader(`interface`); reader.readString() }, run { val reader = WireReader(path); reader.readString() }, run { val reader = WireReader(`data`); AstarteVal.decode(reader) })
    }

    @JvmStatic
    fun on_property_unset(handle: Long, `interface`: ByteBuffer, path: ByteBuffer) {
        val impl = EventListenerHandleMap.get(handle) ?: error("EventListenerHandleMap: invalid handle $handle")
        impl.onPropertyUnset(run { val reader = WireReader(`interface`); reader.readString() }, run { val reader = WireReader(path); reader.readString() })
    }
}

private class EventListenerProxy(private val handle: Long) : EventListener {
    @Suppress("deprecation")
    protected fun finalize() {
        if (handle != 0L) {
            Native.boltffiCallbackEventListenerRelease(handle)
        }
    }


    override fun onConnected() {
        Native.boltffiCallbackEventListenerOnConnected(handle)
    }


    override fun onDisconnected() {
        Native.boltffiCallbackEventListenerOnDisconnected(handle)
    }

    /**
     * Called for Individual datastream events.
     */

    override fun onDataReceived(`interface`: String, path: String, `data`: AstarteVal) {
        val wire_writer_interface = WireWriterPool.acquire((4 + Utf8Codec.maxBytes(`interface`)))
            run {
                val wire = wire_writer_interface.writer
                wire.writeString(`interface`)
            }
        val wire_writer_path = WireWriterPool.acquire((4 + Utf8Codec.maxBytes(path)))
            run {
                val wire = wire_writer_path.writer
                wire.writeString(path)
            }
        val wire_writer_data = WireWriterPool.acquire(`data`.wireEncodedSize())
            run {
                val wire = wire_writer_data.writer
                `data`.wireEncodeTo(wire)
            }
        try {
            Native.boltffiCallbackEventListenerOnDataReceived(handle, wire_writer_interface.buffer, wire_writer_path.buffer, wire_writer_data.buffer)
        } finally {
            wire_writer_interface.close()
            wire_writer_path.close()
            wire_writer_data.close()
        }
    }

    /**
     * Called for Object (aggregate) datastream events. Unsupported fields are silently skipped.
     */

    override fun onObjectReceived(`interface`: String, path: String, entries: List<ObjectEntry>) {
        val wire_writer_interface = WireWriterPool.acquire((4 + Utf8Codec.maxBytes(`interface`)))
            run {
                val wire = wire_writer_interface.writer
                wire.writeString(`interface`)
            }
        val wire_writer_path = WireWriterPool.acquire((4 + Utf8Codec.maxBytes(path)))
            run {
                val wire = wire_writer_path.writer
                wire.writeString(path)
            }
        val wire_writer_entries = WireWriterPool.acquire((4 + entries.sumOf { item -> (item.wireEncodedSize()).toInt() }))
            run {
                val wire = wire_writer_entries.writer
                wire.writeU32(entries.size.toUInt()); entries.forEach { item -> item.wireEncodeTo(wire) }
            }
        try {
            Native.boltffiCallbackEventListenerOnObjectReceived(handle, wire_writer_interface.buffer, wire_writer_path.buffer, wire_writer_entries.buffer)
        } finally {
            wire_writer_interface.close()
            wire_writer_path.close()
            wire_writer_entries.close()
        }
    }

    /**
     * Called when a property is set.
     */

    override fun onPropertyReceived(`interface`: String, path: String, `data`: AstarteVal) {
        val wire_writer_interface = WireWriterPool.acquire((4 + Utf8Codec.maxBytes(`interface`)))
            run {
                val wire = wire_writer_interface.writer
                wire.writeString(`interface`)
            }
        val wire_writer_path = WireWriterPool.acquire((4 + Utf8Codec.maxBytes(path)))
            run {
                val wire = wire_writer_path.writer
                wire.writeString(path)
            }
        val wire_writer_data = WireWriterPool.acquire(`data`.wireEncodedSize())
            run {
                val wire = wire_writer_data.writer
                `data`.wireEncodeTo(wire)
            }
        try {
            Native.boltffiCallbackEventListenerOnPropertyReceived(handle, wire_writer_interface.buffer, wire_writer_path.buffer, wire_writer_data.buffer)
        } finally {
            wire_writer_interface.close()
            wire_writer_path.close()
            wire_writer_data.close()
        }
    }

    /**
     * Called when a property is unset.
     */

    override fun onPropertyUnset(`interface`: String, path: String) {
        val wire_writer_interface = WireWriterPool.acquire((4 + Utf8Codec.maxBytes(`interface`)))
            run {
                val wire = wire_writer_interface.writer
                wire.writeString(`interface`)
            }
        val wire_writer_path = WireWriterPool.acquire((4 + Utf8Codec.maxBytes(path)))
            run {
                val wire = wire_writer_path.writer
                wire.writeString(path)
            }
        try {
            Native.boltffiCallbackEventListenerOnPropertyUnset(handle, wire_writer_interface.buffer, wire_writer_path.buffer)
        } finally {
            wire_writer_interface.close()
            wire_writer_path.close()
        }
    }
}

object EventListenerBridge {
    private val registered = java.util.concurrent.atomic.AtomicBoolean(false)

    fun register() {
        if (!registered.compareAndSet(false, true)) return
    }

    fun create(impl: EventListener): Long {
        register()
        return EventListenerHandleMap.insert(impl)
    }

    fun wrap(handle: Long): EventListener {
        return EventListenerHandleMap.get(handle) ?: EventListenerProxy(handle)
    }
}

@Suppress("FunctionName")
private object Native {
    init {
        val preferredLibrary = "astarte-device-sdk-bindings_jni"
        val fallbackLibrary = "astarte-device-sdk-bindings"
        val vmName = System.getProperty("java.vm.name").orEmpty()
        val isAndroidRuntime =
            vmName.contains("dalvik", ignoreCase = true) ||
            vmName.contains("art", ignoreCase = true)
        if (isAndroidRuntime) {
            System.loadLibrary(fallbackLibrary)
        } else {
            System.loadLibrary(preferredLibrary)
        }
    }

    @JvmStatic external fun boltffi_free_string(ptr: Long)
    @JvmStatic external fun boltffi_last_error_message(): ByteArray

    @JvmStatic fun boltffiFutureContinuationCallback(handle: Long, pollResult: Byte) {
        val continuation = boltffiContinuationMap.tryRemove(handle)
        if (continuation == null) {
            System.err.println("BoltFFI: boltffiFutureContinuationCallback: handle $handle not found (already completed or cancelled)")
            return
        }
        BoltFFIScope.launch {
            try {
                continuation.resume(pollResult)
            } catch (e: Exception) {
                System.err.println("BoltFFI: boltffiFutureContinuationCallback: resume failed for handle $handle: $e")
            }
        }
    }
    @JvmStatic external fun boltffi_astarte_device_new(config: ByteBuffer, interfaces_dir: ByteArray): Long
    @JvmStatic external fun boltffi_astarte_device_free(handle: Long)
    @JvmStatic external fun boltffi_astarte_device_send(handle: Long, interface_name: ByteArray, interface_path: ByteArray, data: ByteBuffer): Unit
    @JvmStatic external fun boltffi_astarte_device_start_listening(handle: Long, listener: Long): Unit
    @JvmStatic external fun boltffi_astarte_device_disconenct(handle: Long): Unit
    @JvmStatic external fun boltffiCallbackEventListenerRelease(handle: Long)
    @JvmStatic external fun boltffiCallbackEventListenerOnConnected(handle: Long): Unit
    @JvmStatic external fun boltffiCallbackEventListenerOnDisconnected(handle: Long): Unit
    @JvmStatic external fun boltffiCallbackEventListenerOnDataReceived(handle: Long, `interface`: ByteBuffer, path: ByteBuffer, data: ByteBuffer): Unit
    @JvmStatic external fun boltffiCallbackEventListenerOnObjectReceived(handle: Long, `interface`: ByteBuffer, path: ByteBuffer, entries: ByteBuffer): Unit
    @JvmStatic external fun boltffiCallbackEventListenerOnPropertyReceived(handle: Long, `interface`: ByteBuffer, path: ByteBuffer, data: ByteBuffer): Unit
    @JvmStatic external fun boltffiCallbackEventListenerOnPropertyUnset(handle: Long, `interface`: ByteBuffer, path: ByteBuffer): Unit
}
