// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System;
using System.Text;

namespace AstarteDeviceSdkBindings
{
    /// <summary>
    /// Connection credentials and pairing configuration for an Astarte device.
    /// </summary>
    /// <param name="Realm">The Astarte realm name the device belongs to.</param>
    /// <param name="DeviceId">The unique device identifier (Base64-encoded 128-bit UUID).</param>
    /// <param name="CredentialsSecret">The device credentials secret used for MQTT authentication.</param>
    /// <param name="PairingUrl">The Astarte Pairing API base URL (e.g. <c>http://api.astarte.example/pairing</c>).</param>
    /// <param name="IgnoreSsl">
    /// When <see langword="true"/>, TLS certificate validation is skipped.
    /// Use only in development or testing environments.
    /// </param>
    public readonly record struct AstarteConfig(
        string Realm,
        string DeviceId,
        string CredentialsSecret,
        string PairingUrl,
        bool IgnoreSsl
    )
    {
        internal static AstarteConfig Decode(WireReader reader) =>
            new AstarteConfig(
                reader.ReadString(),
                reader.ReadString(),
                reader.ReadString(),
                reader.ReadString(),
                reader.ReadBool()
            );

        internal int WireEncodedSize() =>
            (4 + Encoding.UTF8.GetByteCount(this.Realm)) +
            (4 + Encoding.UTF8.GetByteCount(this.DeviceId)) +
            (4 + Encoding.UTF8.GetByteCount(this.CredentialsSecret)) +
            (4 + Encoding.UTF8.GetByteCount(this.PairingUrl)) +
            1;

        internal void WireEncodeTo(WireWriter wire)
        {
            wire.WriteString(this.Realm);
            wire.WriteString(this.DeviceId);
            wire.WriteString(this.CredentialsSecret);
            wire.WriteString(this.PairingUrl);
            wire.WriteBool(this.IgnoreSsl);
        }
    }
}