// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System;
using System.Text;

namespace AstarteDeviceSdkBindings
{
    /// <summary>
    /// Discriminated union of all value types supported by the Astarte Device SDK.
    /// Use pattern matching to inspect the active variant.
    /// </summary>
    /// <remarks>
    /// Variants that carry array fields (<see cref="BinaryBlob"/>, <see cref="DoubleArray"/>,
    /// <see cref="IntegerArray"/>, <see cref="BooleanArray"/>, <see cref="LongIntegerArray"/>,
    /// <see cref="StringArray"/>, <see cref="DateTimeArray"/>) are C# <c>record</c> types.
    /// C# records use reference equality for array fields, so two instances with identical
    /// content are not record-equal — compare <c>.Value</c> directly when structural
    /// equality is needed.
    /// </remarks>
    public abstract record AstarteVal
    {
        private AstarteVal() { }

        /// <summary>A 64-bit IEEE 754 floating-point value.</summary>
        /// <param name="Value">The double-precision floating-point number.</param>
        public sealed record Double(
            double Value
        ) : AstarteVal;

        /// <summary>A 32-bit signed integer value.</summary>
        /// <param name="Value">The integer.</param>
        public sealed record Integer(
            int Value
        ) : AstarteVal;

        /// <summary>A boolean value.</summary>
        /// <param name="Value">The boolean.</param>
        public sealed record Boolean(
            bool Value
        ) : AstarteVal;

        /// <summary>A 64-bit signed integer value.</summary>
        /// <param name="Value">The long integer.</param>
        public sealed record LongInteger(
            long Value
        ) : AstarteVal;

        /// <summary>A UTF-8 string value. Named <c>IString</c> to avoid shadowing <see cref="System.String"/>.</summary>
        /// <param name="Value">The string.</param>
        public sealed record IString(
            string Value
        ) : AstarteVal;

        /// <summary>
        /// A raw binary blob.
        /// <para>
        /// Note: two <c>BinaryBlob</c> instances with the same byte content are not record-equal
        /// because C# records use reference equality for arrays. Compare <c>.Value</c> directly.
        /// </para>
        /// </summary>
        /// <param name="Value">The raw bytes.</param>
        public sealed record BinaryBlob(
            byte[] Value
        ) : AstarteVal;

        /// <summary>A point in time represented as milliseconds since the Unix epoch (UTC).</summary>
        /// <param name="Value">Milliseconds since 1970-01-01T00:00:00Z.</param>
        public sealed record DateTime(
            long Value
        ) : AstarteVal;

        /// <summary>An array of 64-bit floating-point values.</summary>
        /// <param name="Value">The elements.</param>
        public sealed record DoubleArray(
            double[] Value
        ) : AstarteVal;

        /// <summary>An array of 32-bit signed integer values.</summary>
        /// <param name="Value">The elements.</param>
        public sealed record IntegerArray(
            int[] Value
        ) : AstarteVal;

        /// <summary>An array of boolean values.</summary>
        /// <param name="Value">The elements.</param>
        public sealed record BooleanArray(
            bool[] Value
        ) : AstarteVal;

        /// <summary>An array of 64-bit signed integer values.</summary>
        /// <param name="Value">The elements.</param>
        public sealed record LongIntegerArray(
            long[] Value
        ) : AstarteVal;

        /// <summary>An array of UTF-8 string values.</summary>
        /// <param name="Value">The elements.</param>
        public sealed record StringArray(
            string[] Value
        ) : AstarteVal;

        /// <summary>An array of timestamps, each as milliseconds since the Unix epoch (UTC).</summary>
        /// <param name="Value">The elements, each in milliseconds since 1970-01-01T00:00:00Z.</param>
        public sealed record DateTimeArray(
            long[] Value
        ) : AstarteVal;

        internal static AstarteVal Decode(WireReader reader) =>
            reader.ReadI32() switch
            {
                0 => new Double(
                    reader.ReadF64()
                ),
                1 => new Integer(
                    reader.ReadI32()
                ),
                2 => new Boolean(
                    reader.ReadBool()
                ),
                3 => new LongInteger(
                    reader.ReadI64()
                ),
                4 => new IString(
                    reader.ReadString()
                ),
                5 => new BinaryBlob(
                    reader.ReadLengthPrefixedBlittableArray<byte>()
                ),
                6 => new DateTime(
                    reader.ReadI64()
                ),
                7 => new DoubleArray(
                    reader.ReadLengthPrefixedBlittableArray<double>()
                ),
                8 => new IntegerArray(
                    reader.ReadLengthPrefixedBlittableArray<int>()
                ),
                9 => new BooleanArray(
                    reader.ReadLengthPrefixedBoolArray()
                ),
                10 => new LongIntegerArray(
                    reader.ReadLengthPrefixedBlittableArray<long>()
                ),
                11 => new StringArray(
                    reader.ReadEncodedArray<string>(r0 => r0.ReadString())
                ),
                12 => new DateTimeArray(
                    reader.ReadLengthPrefixedBlittableArray<long>()
                ),
                int tag => throw new InvalidOperationException($"Unknown AstarteVal tag: {tag}"),
            };

        internal int WireEncodedSize() => 4 + this switch
        {
            Double _v => 8,
            Integer _v => 4,
            Boolean _v => 1,
            LongInteger _v => 8,
            IString _v => (4 + Encoding.UTF8.GetByteCount(_v.Value)),
            BinaryBlob _v => (4 + _v.Value.Length),
            DateTime _v => 8,
            DoubleArray _v => (4 + _v.Value.Length * 8),
            IntegerArray _v => (4 + _v.Value.Length * 4),
            BooleanArray _v => (4 + _v.Value.Length * 1),
            LongIntegerArray _v => (4 + _v.Value.Length * 8),
            StringArray _v => WireWriter.EncodedArraySize(_v.Value, sizeItem0 => (4 + Encoding.UTF8.GetByteCount(sizeItem0))),
            DateTimeArray _v => (4 + _v.Value.Length * 8),
            _ => throw new InvalidOperationException($"Unknown AstarteVal variant"),
        };

        internal void WireEncodeTo(WireWriter wire)
        {
            switch (this)
            {
                case Double _v:
                    wire.WriteI32(0);
                    wire.WriteF64(_v.Value);
                    break;
                case Integer _v:
                    wire.WriteI32(1);
                    wire.WriteI32(_v.Value);
                    break;
                case Boolean _v:
                    wire.WriteI32(2);
                    wire.WriteBool(_v.Value);
                    break;
                case LongInteger _v:
                    wire.WriteI32(3);
                    wire.WriteI64(_v.Value);
                    break;
                case IString _v:
                    wire.WriteI32(4);
                    wire.WriteString(_v.Value);
                    break;
                case BinaryBlob _v:
                    wire.WriteI32(5);
                    wire.WriteBlittableArray(_v.Value);
                    break;
                case DateTime _v:
                    wire.WriteI32(6);
                    wire.WriteI64(_v.Value);
                    break;
                case DoubleArray _v:
                    wire.WriteI32(7);
                    wire.WriteBlittableArray(_v.Value);
                    break;
                case IntegerArray _v:
                    wire.WriteI32(8);
                    wire.WriteBlittableArray(_v.Value);
                    break;
                case BooleanArray _v:
                    wire.WriteI32(9);
                    wire.WriteBoolArray(_v.Value);
                    break;
                case LongIntegerArray _v:
                    wire.WriteI32(10);
                    wire.WriteBlittableArray(_v.Value);
                    break;
                case StringArray _v:
                    wire.WriteI32(11);
                    wire.WriteI32(_v.Value.Length);
                    foreach (string item0 in _v.Value) { wire.WriteString(item0); };
                    break;
                case DateTimeArray _v:
                    wire.WriteI32(12);
                    wire.WriteBlittableArray(_v.Value);
                    break;
            }
        }
    }
}