// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System;
using System.Text;

namespace AstarteDeviceSdkBindings
{
    /// <summary>
    /// Simplified configuration record.
    /// </summary>
    public readonly record struct AstarteConfig(
        string Realm,
        string DeviceId,
        string CredentialsSecret,
        string PairingUrl,
        bool IgnoreSsl
    )
    {
        internal static AstarteConfig Decode(WireReader reader) =>
            new AstarteConfig(
                reader.ReadString(),
                reader.ReadString(),
                reader.ReadString(),
                reader.ReadString(),
                reader.ReadBool()
            );

        internal int WireEncodedSize() =>
            (4 + Encoding.UTF8.GetByteCount(this.Realm)) +
            (4 + Encoding.UTF8.GetByteCount(this.DeviceId)) +
            (4 + Encoding.UTF8.GetByteCount(this.CredentialsSecret)) +
            (4 + Encoding.UTF8.GetByteCount(this.PairingUrl)) +
            1;

        internal void WireEncodeTo(WireWriter wire)
        {
            wire.WriteString(this.Realm);
            wire.WriteString(this.DeviceId);
            wire.WriteString(this.CredentialsSecret);
            wire.WriteString(this.PairingUrl);
            wire.WriteBool(this.IgnoreSsl);
        }
    }
}