// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// Post-generation fix applied: added public constructor (boltffi_astarte_device_new).
// </auto-generated>
#nullable enable

using System;
using System.Threading;
using System.Text;
using System.Runtime.InteropServices;

namespace AstarteDeviceSdkBindings
{
    public sealed class AstarteDevice : IDisposable
    {
        private IntPtr _handle;

        // Private handle-adopting ctor; used only by chained `: this(...)` and the static factories below.
        private AstarteDevice(IntPtr handle)
        {
            _handle = handle;
        }

        public AstarteDevice(AstarteConfig config, string interfacesDir)
            : this(CreateHandle(config, interfacesDir)) { }

        private static IntPtr CreateHandle(AstarteConfig config, string interfacesDir)
        {
            using var configWire = new WireWriter(config.WireEncodedSize());
            config.WireEncodeTo(configWire);
            byte[] configBytes = configWire.ToArray();
            byte[] dirBytes = Encoding.UTF8.GetBytes(interfacesDir);
            IntPtr handle = NativeMethods.AstarteDeviceNew(
                configBytes, (UIntPtr)configBytes.Length,
                dirBytes, (UIntPtr)dirBytes.Length);
            if (handle == IntPtr.Zero)
                throw new SdkErrorException(new SdkError.Config("Failed to create AstarteDevice: check credentials and pairing URL"));
            return handle;
        }

        public void Send(string interfaceName, string interfacePath, AstarteVal data)
        {
            ThrowIfDisposed();
            byte[] _interfaceNameBytes = Encoding.UTF8.GetBytes(interfaceName);
            byte[] _interfacePathBytes = Encoding.UTF8.GetBytes(interfacePath);
            using var _wire_data = new WireWriter(data.WireEncodedSize());
            data.WireEncodeTo(_wire_data);
            byte[] _dataBytes = _wire_data.ToArray();
            NativeMethods.AstarteDeviceSend(_handle, _interfaceNameBytes, (UIntPtr)_interfaceNameBytes.Length, _interfacePathBytes, (UIntPtr)_interfacePathBytes.Length, _dataBytes, (UIntPtr)_dataBytes.Length);
        }

        public void StartListening(EventListener listener)
        {
            ThrowIfDisposed();
            NativeMethods.AstarteDeviceStartListening(_handle, EventListenerBridge.Create(listener));
        }

        public void Disconenct()
        {
            ThrowIfDisposed();
            NativeMethods.AstarteDeviceDisconenct(_handle);
        }

        internal IntPtr RawHandle => _handle;

        private void ThrowIfDisposed()
        {
            if (_handle == IntPtr.Zero) throw new ObjectDisposedException(nameof(AstarteDevice));
        }

        public void Dispose()
        {
            IntPtr handle = Interlocked.Exchange(ref _handle, IntPtr.Zero);
            if (handle == IntPtr.Zero) return;
            NativeMethods.AstarteDeviceFree(handle);
            GC.SuppressFinalize(this);
        }

        ~AstarteDevice()
        {
            Dispose();
        }
    }
}