// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System;
using System.Runtime.InteropServices;
using System.Buffers;
using System.Buffers.Binary;
using System.Runtime.CompilerServices;
using System.Text;

namespace AstarteDeviceSdkBindings
{
    public interface EventListener
    {

        void OnConnected();

        void OnDisconnected();

        void OnDataReceived(string @interface, string path, AstarteVal data);

        void OnObjectReceived(string @interface, string path, ObjectEntry[] entries);

        void OnPropertyReceived(string @interface, string path, AstarteVal data);

        void OnPropertyUnset(string @interface, string path);

    }
    public sealed class EventListenerProxy : EventListener, global::System.IDisposable
    {
        private BoltFFICallbackHandle _handle;

        internal EventListenerProxy(BoltFFICallbackHandle handle)
        {
            _handle = handle;
        }

        ~EventListenerProxy()
        {
            Release();
        }

        public void Dispose()
        {
            Release();
            global::System.GC.SuppressFinalize(this);
        }

        internal BoltFFICallbackHandle CloneHandle()
        {
            if (_handle.IsNull) return BoltFFICallbackHandle.Null;
            EventListenerBridge.VTable table = Marshal.PtrToStructure<EventListenerBridge.VTable>(_handle.vtable);
            var clone = Marshal.GetDelegateForFunctionPointer<EventListenerBridge.CloneFn>(table.clone);
            ulong cloned = clone(_handle.handle);
            return cloned == 0 ? BoltFFICallbackHandle.Null : new BoltFFICallbackHandle { handle = cloned, vtable = _handle.vtable };
        }

        private void Release()
        {
            if (_handle.IsNull) return;
            EventListenerBridge.VTable table = Marshal.PtrToStructure<EventListenerBridge.VTable>(_handle.vtable);
            var free = Marshal.GetDelegateForFunctionPointer<EventListenerBridge.FreeFn>(table.free);
            ulong handle = _handle.handle;
            _handle = BoltFFICallbackHandle.Null;
            free(handle);
        }


        public void OnConnected()
        {
            if (_handle.IsNull) throw new ObjectDisposedException(nameof(EventListenerProxy));
            EventListenerBridge.VTable __boltffiTable = Marshal.PtrToStructure<EventListenerBridge.VTable>(_handle.vtable);
            var __boltffiInvoke = Marshal.GetDelegateForFunctionPointer<EventListenerBridge.OnConnectedProxyFn>(__boltffiTable.on_connected);
            FfiStatus __boltffiStatus;
            __boltffiInvoke(_handle.handle, out __boltffiStatus);
            EventListenerBridge.ThrowIfCallbackStatus(__boltffiStatus);
        }

        public void OnDisconnected()
        {
            if (_handle.IsNull) throw new ObjectDisposedException(nameof(EventListenerProxy));
            EventListenerBridge.VTable __boltffiTable = Marshal.PtrToStructure<EventListenerBridge.VTable>(_handle.vtable);
            var __boltffiInvoke = Marshal.GetDelegateForFunctionPointer<EventListenerBridge.OnDisconnectedProxyFn>(__boltffiTable.on_disconnected);
            FfiStatus __boltffiStatus;
            __boltffiInvoke(_handle.handle, out __boltffiStatus);
            EventListenerBridge.ThrowIfCallbackStatus(__boltffiStatus);
        }

        public void OnDataReceived(string @interface, string path, AstarteVal data)
        {
            if (_handle.IsNull) throw new ObjectDisposedException(nameof(EventListenerProxy));
            EventListenerBridge.VTable __boltffiTable = Marshal.PtrToStructure<EventListenerBridge.VTable>(_handle.vtable);
            var __boltffiInvoke = Marshal.GetDelegateForFunctionPointer<EventListenerBridge.OnDataReceivedProxyFn>(__boltffiTable.on_data_received);
            byte[] _interfaceBytes;
            using (var _interfaceWire = new WireWriter((4 + Encoding.UTF8.GetByteCount(@interface))))
            {
                _interfaceWire.WriteString(@interface);
                _interfaceBytes = _interfaceWire.ToArray();
            }
            GCHandle _interfacePin = default;
            IntPtr _interfacePtr = IntPtr.Zero;
            byte[] _pathBytes;
            using (var _pathWire = new WireWriter((4 + Encoding.UTF8.GetByteCount(path))))
            {
                _pathWire.WriteString(path);
                _pathBytes = _pathWire.ToArray();
            }
            GCHandle _pathPin = default;
            IntPtr _pathPtr = IntPtr.Zero;
            byte[] _dataBytes;
            using (var _dataWire = new WireWriter(data.WireEncodedSize()))
            {
                data.WireEncodeTo(_dataWire);
                _dataBytes = _dataWire.ToArray();
            }
            GCHandle _dataPin = default;
            IntPtr _dataPtr = IntPtr.Zero;
            try
            {
                if (_interfaceBytes.Length != 0)
                {
                    _interfacePin = GCHandle.Alloc(_interfaceBytes, GCHandleType.Pinned);
                    _interfacePtr = _interfacePin.AddrOfPinnedObject();
                }
                if (_pathBytes.Length != 0)
                {
                    _pathPin = GCHandle.Alloc(_pathBytes, GCHandleType.Pinned);
                    _pathPtr = _pathPin.AddrOfPinnedObject();
                }
                if (_dataBytes.Length != 0)
                {
                    _dataPin = GCHandle.Alloc(_dataBytes, GCHandleType.Pinned);
                    _dataPtr = _dataPin.AddrOfPinnedObject();
                }
                FfiStatus __boltffiStatus;
                __boltffiInvoke(_handle.handle, _interfacePtr, (UIntPtr)_interfaceBytes.Length, _pathPtr, (UIntPtr)_pathBytes.Length, _dataPtr, (UIntPtr)_dataBytes.Length, out __boltffiStatus);
                EventListenerBridge.ThrowIfCallbackStatus(__boltffiStatus);
            }
            finally
            {
                if (_interfacePin.IsAllocated) _interfacePin.Free();
                if (_pathPin.IsAllocated) _pathPin.Free();
                if (_dataPin.IsAllocated) _dataPin.Free();
            }
        }

        public void OnObjectReceived(string @interface, string path, ObjectEntry[] entries)
        {
            if (_handle.IsNull) throw new ObjectDisposedException(nameof(EventListenerProxy));
            EventListenerBridge.VTable __boltffiTable = Marshal.PtrToStructure<EventListenerBridge.VTable>(_handle.vtable);
            var __boltffiInvoke = Marshal.GetDelegateForFunctionPointer<EventListenerBridge.OnObjectReceivedProxyFn>(__boltffiTable.on_object_received);
            byte[] _interfaceBytes;
            using (var _interfaceWire = new WireWriter((4 + Encoding.UTF8.GetByteCount(@interface))))
            {
                _interfaceWire.WriteString(@interface);
                _interfaceBytes = _interfaceWire.ToArray();
            }
            GCHandle _interfacePin = default;
            IntPtr _interfacePtr = IntPtr.Zero;
            byte[] _pathBytes;
            using (var _pathWire = new WireWriter((4 + Encoding.UTF8.GetByteCount(path))))
            {
                _pathWire.WriteString(path);
                _pathBytes = _pathWire.ToArray();
            }
            GCHandle _pathPin = default;
            IntPtr _pathPtr = IntPtr.Zero;
            byte[] _entriesBytes;
            using (var _entriesWire = new WireWriter(WireWriter.EncodedArraySize(entries, sizeItem0 => sizeItem0.WireEncodedSize())))
            {
                _entriesWire.WriteI32(entries.Length);
                foreach (ObjectEntry item0 in entries) { item0.WireEncodeTo(_entriesWire); };
                _entriesBytes = _entriesWire.ToArray();
            }
            GCHandle _entriesPin = default;
            IntPtr _entriesPtr = IntPtr.Zero;
            try
            {
                if (_interfaceBytes.Length != 0)
                {
                    _interfacePin = GCHandle.Alloc(_interfaceBytes, GCHandleType.Pinned);
                    _interfacePtr = _interfacePin.AddrOfPinnedObject();
                }
                if (_pathBytes.Length != 0)
                {
                    _pathPin = GCHandle.Alloc(_pathBytes, GCHandleType.Pinned);
                    _pathPtr = _pathPin.AddrOfPinnedObject();
                }
                if (_entriesBytes.Length != 0)
                {
                    _entriesPin = GCHandle.Alloc(_entriesBytes, GCHandleType.Pinned);
                    _entriesPtr = _entriesPin.AddrOfPinnedObject();
                }
                FfiStatus __boltffiStatus;
                __boltffiInvoke(_handle.handle, _interfacePtr, (UIntPtr)_interfaceBytes.Length, _pathPtr, (UIntPtr)_pathBytes.Length, _entriesPtr, (UIntPtr)_entriesBytes.Length, out __boltffiStatus);
                EventListenerBridge.ThrowIfCallbackStatus(__boltffiStatus);
            }
            finally
            {
                if (_interfacePin.IsAllocated) _interfacePin.Free();
                if (_pathPin.IsAllocated) _pathPin.Free();
                if (_entriesPin.IsAllocated) _entriesPin.Free();
            }
        }

        public void OnPropertyReceived(string @interface, string path, AstarteVal data)
        {
            if (_handle.IsNull) throw new ObjectDisposedException(nameof(EventListenerProxy));
            EventListenerBridge.VTable __boltffiTable = Marshal.PtrToStructure<EventListenerBridge.VTable>(_handle.vtable);
            var __boltffiInvoke = Marshal.GetDelegateForFunctionPointer<EventListenerBridge.OnPropertyReceivedProxyFn>(__boltffiTable.on_property_received);
            byte[] _interfaceBytes;
            using (var _interfaceWire = new WireWriter((4 + Encoding.UTF8.GetByteCount(@interface))))
            {
                _interfaceWire.WriteString(@interface);
                _interfaceBytes = _interfaceWire.ToArray();
            }
            GCHandle _interfacePin = default;
            IntPtr _interfacePtr = IntPtr.Zero;
            byte[] _pathBytes;
            using (var _pathWire = new WireWriter((4 + Encoding.UTF8.GetByteCount(path))))
            {
                _pathWire.WriteString(path);
                _pathBytes = _pathWire.ToArray();
            }
            GCHandle _pathPin = default;
            IntPtr _pathPtr = IntPtr.Zero;
            byte[] _dataBytes;
            using (var _dataWire = new WireWriter(data.WireEncodedSize()))
            {
                data.WireEncodeTo(_dataWire);
                _dataBytes = _dataWire.ToArray();
            }
            GCHandle _dataPin = default;
            IntPtr _dataPtr = IntPtr.Zero;
            try
            {
                if (_interfaceBytes.Length != 0)
                {
                    _interfacePin = GCHandle.Alloc(_interfaceBytes, GCHandleType.Pinned);
                    _interfacePtr = _interfacePin.AddrOfPinnedObject();
                }
                if (_pathBytes.Length != 0)
                {
                    _pathPin = GCHandle.Alloc(_pathBytes, GCHandleType.Pinned);
                    _pathPtr = _pathPin.AddrOfPinnedObject();
                }
                if (_dataBytes.Length != 0)
                {
                    _dataPin = GCHandle.Alloc(_dataBytes, GCHandleType.Pinned);
                    _dataPtr = _dataPin.AddrOfPinnedObject();
                }
                FfiStatus __boltffiStatus;
                __boltffiInvoke(_handle.handle, _interfacePtr, (UIntPtr)_interfaceBytes.Length, _pathPtr, (UIntPtr)_pathBytes.Length, _dataPtr, (UIntPtr)_dataBytes.Length, out __boltffiStatus);
                EventListenerBridge.ThrowIfCallbackStatus(__boltffiStatus);
            }
            finally
            {
                if (_interfacePin.IsAllocated) _interfacePin.Free();
                if (_pathPin.IsAllocated) _pathPin.Free();
                if (_dataPin.IsAllocated) _dataPin.Free();
            }
        }

        public void OnPropertyUnset(string @interface, string path)
        {
            if (_handle.IsNull) throw new ObjectDisposedException(nameof(EventListenerProxy));
            EventListenerBridge.VTable __boltffiTable = Marshal.PtrToStructure<EventListenerBridge.VTable>(_handle.vtable);
            var __boltffiInvoke = Marshal.GetDelegateForFunctionPointer<EventListenerBridge.OnPropertyUnsetProxyFn>(__boltffiTable.on_property_unset);
            byte[] _interfaceBytes;
            using (var _interfaceWire = new WireWriter((4 + Encoding.UTF8.GetByteCount(@interface))))
            {
                _interfaceWire.WriteString(@interface);
                _interfaceBytes = _interfaceWire.ToArray();
            }
            GCHandle _interfacePin = default;
            IntPtr _interfacePtr = IntPtr.Zero;
            byte[] _pathBytes;
            using (var _pathWire = new WireWriter((4 + Encoding.UTF8.GetByteCount(path))))
            {
                _pathWire.WriteString(path);
                _pathBytes = _pathWire.ToArray();
            }
            GCHandle _pathPin = default;
            IntPtr _pathPtr = IntPtr.Zero;
            try
            {
                if (_interfaceBytes.Length != 0)
                {
                    _interfacePin = GCHandle.Alloc(_interfaceBytes, GCHandleType.Pinned);
                    _interfacePtr = _interfacePin.AddrOfPinnedObject();
                }
                if (_pathBytes.Length != 0)
                {
                    _pathPin = GCHandle.Alloc(_pathBytes, GCHandleType.Pinned);
                    _pathPtr = _pathPin.AddrOfPinnedObject();
                }
                FfiStatus __boltffiStatus;
                __boltffiInvoke(_handle.handle, _interfacePtr, (UIntPtr)_interfaceBytes.Length, _pathPtr, (UIntPtr)_pathBytes.Length, out __boltffiStatus);
                EventListenerBridge.ThrowIfCallbackStatus(__boltffiStatus);
            }
            finally
            {
                if (_interfacePin.IsAllocated) _interfacePin.Free();
                if (_pathPin.IsAllocated) _pathPin.Free();
            }
        }

    }
    internal static unsafe class EventListenerBridge
    {
        private static readonly global::System.Collections.Concurrent.ConcurrentDictionary<ulong, EventListener> Handles = new();
        private static long _nextHandle = -1;
        private static readonly IntPtr VTablePtr;

        static EventListenerBridge()
        {
            VTable table = new VTable
            {
                free = Marshal.GetFunctionPointerForDelegate(FreeDelegate),
                clone = Marshal.GetFunctionPointerForDelegate(CloneDelegate),
                on_connected = Marshal.GetFunctionPointerForDelegate(OnConnectedDelegate),
                on_disconnected = Marshal.GetFunctionPointerForDelegate(OnDisconnectedDelegate),
                on_data_received = Marshal.GetFunctionPointerForDelegate(OnDataReceivedDelegate),
                on_object_received = Marshal.GetFunctionPointerForDelegate(OnObjectReceivedDelegate),
                on_property_received = Marshal.GetFunctionPointerForDelegate(OnPropertyReceivedDelegate),
                on_property_unset = Marshal.GetFunctionPointerForDelegate(OnPropertyUnsetDelegate)
            };
            VTablePtr = (IntPtr)NativeMemory.Alloc((nuint)Marshal.SizeOf<VTable>());
            Marshal.StructureToPtr(table, VTablePtr, false);
            RegisterNative(VTablePtr);
        }

        internal static BoltFFICallbackHandle Create(EventListener? impl_)
        {
            _ = VTablePtr;
            if (impl_ is null) return BoltFFICallbackHandle.Null;
            if (impl_ is EventListenerProxy proxy) return proxy.CloneHandle();
            return CreateNative(Insert(impl_));
        }

        internal static EventListenerProxy Wrap(BoltFFICallbackHandle handle)
        {
            if (handle.IsNull) throw new InvalidOperationException("callback handle is null");
            return new EventListenerProxy(handle);
        }

        private static ulong Insert(EventListener impl_)
        {
            ulong handle = unchecked((ulong)global::System.Threading.Interlocked.Add(ref _nextHandle, 2));
            Handles[handle] = impl_;
            return handle;
        }

        private static void Free(ulong handle) => Handles.TryRemove(handle, out _);

        private static ulong Clone(ulong handle)
        {
            return Handles.TryGetValue(handle, out EventListener? impl_) ? Insert(impl_) : 0;
        }

        internal static void ThrowIfCallbackStatus(FfiStatus status)
        {
            if (status.code != 0) throw new InvalidOperationException($"callback failed with status code {status.code}");
        }


        private static void OnConnected(ulong handle, out FfiStatus __boltffiStatus)
        {
            __boltffiStatus = new FfiStatus { code = 100 };
            try
            {
                if (!Handles.TryGetValue(handle, out var impl_)) throw new InvalidOperationException("invalid callback handle");
                impl_.OnConnected();
                __boltffiStatus = new FfiStatus { code = 0 };
            }
            catch
            {
                __boltffiStatus = new FfiStatus { code = 100 };
            }
        }

        private static void OnDisconnected(ulong handle, out FfiStatus __boltffiStatus)
        {
            __boltffiStatus = new FfiStatus { code = 100 };
            try
            {
                if (!Handles.TryGetValue(handle, out var impl_)) throw new InvalidOperationException("invalid callback handle");
                impl_.OnDisconnected();
                __boltffiStatus = new FfiStatus { code = 0 };
            }
            catch
            {
                __boltffiStatus = new FfiStatus { code = 100 };
            }
        }

        private static void OnDataReceived(ulong handle, IntPtr @interface, UIntPtr interfaceLen, IntPtr path, UIntPtr pathLen, IntPtr data, UIntPtr dataLen, out FfiStatus __boltffiStatus)
        {
            __boltffiStatus = new FfiStatus { code = 100 };
            try
            {
                if (!Handles.TryGetValue(handle, out var impl_)) throw new InvalidOperationException("invalid callback handle");
                var __boltffiinterfaceReader = new WireReader(@interface, interfaceLen);
                var __boltffipathReader = new WireReader(path, pathLen);
                var __boltffidataReader = new WireReader(data, dataLen);
                impl_.OnDataReceived(__boltffiinterfaceReader.ReadString(), __boltffipathReader.ReadString(), AstarteVal.Decode(__boltffidataReader));
                __boltffiStatus = new FfiStatus { code = 0 };
            }
            catch
            {
                __boltffiStatus = new FfiStatus { code = 100 };
            }
        }

        private static void OnObjectReceived(ulong handle, IntPtr @interface, UIntPtr interfaceLen, IntPtr path, UIntPtr pathLen, IntPtr entries, UIntPtr entriesLen, out FfiStatus __boltffiStatus)
        {
            __boltffiStatus = new FfiStatus { code = 100 };
            try
            {
                if (!Handles.TryGetValue(handle, out var impl_)) throw new InvalidOperationException("invalid callback handle");
                var __boltffiinterfaceReader = new WireReader(@interface, interfaceLen);
                var __boltffipathReader = new WireReader(path, pathLen);
                var __boltffientriesReader = new WireReader(entries, entriesLen);
                impl_.OnObjectReceived(__boltffiinterfaceReader.ReadString(), __boltffipathReader.ReadString(), __boltffientriesReader.ReadEncodedArray<ObjectEntry>(r0 => ObjectEntry.Decode(r0)));
                __boltffiStatus = new FfiStatus { code = 0 };
            }
            catch
            {
                __boltffiStatus = new FfiStatus { code = 100 };
            }
        }

        private static void OnPropertyReceived(ulong handle, IntPtr @interface, UIntPtr interfaceLen, IntPtr path, UIntPtr pathLen, IntPtr data, UIntPtr dataLen, out FfiStatus __boltffiStatus)
        {
            __boltffiStatus = new FfiStatus { code = 100 };
            try
            {
                if (!Handles.TryGetValue(handle, out var impl_)) throw new InvalidOperationException("invalid callback handle");
                var __boltffiinterfaceReader = new WireReader(@interface, interfaceLen);
                var __boltffipathReader = new WireReader(path, pathLen);
                var __boltffidataReader = new WireReader(data, dataLen);
                impl_.OnPropertyReceived(__boltffiinterfaceReader.ReadString(), __boltffipathReader.ReadString(), AstarteVal.Decode(__boltffidataReader));
                __boltffiStatus = new FfiStatus { code = 0 };
            }
            catch
            {
                __boltffiStatus = new FfiStatus { code = 100 };
            }
        }

        private static void OnPropertyUnset(ulong handle, IntPtr @interface, UIntPtr interfaceLen, IntPtr path, UIntPtr pathLen, out FfiStatus __boltffiStatus)
        {
            __boltffiStatus = new FfiStatus { code = 100 };
            try
            {
                if (!Handles.TryGetValue(handle, out var impl_)) throw new InvalidOperationException("invalid callback handle");
                var __boltffiinterfaceReader = new WireReader(@interface, interfaceLen);
                var __boltffipathReader = new WireReader(path, pathLen);
                impl_.OnPropertyUnset(__boltffiinterfaceReader.ReadString(), __boltffipathReader.ReadString());
                __boltffiStatus = new FfiStatus { code = 0 };
            }
            catch
            {
                __boltffiStatus = new FfiStatus { code = 100 };
            }
        }



        [StructLayout(LayoutKind.Sequential)]
        internal struct VTable
        {
            public IntPtr free;
            public IntPtr clone;

            public IntPtr on_connected;

            public IntPtr on_disconnected;

            public IntPtr on_data_received;

            public IntPtr on_object_received;

            public IntPtr on_property_received;

            public IntPtr on_property_unset;

        }

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void FreeFn(ulong handle);
        private static readonly FreeFn FreeDelegate = Free;

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate ulong CloneFn(ulong handle);
        private static readonly CloneFn CloneDelegate = Clone;


        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate void OnConnectedFn(ulong handle, out FfiStatus __boltffiStatus);
        private static readonly OnConnectedFn OnConnectedDelegate = OnConnected;
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void OnConnectedProxyFn(ulong handle, out FfiStatus __boltffiStatus);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate void OnDisconnectedFn(ulong handle, out FfiStatus __boltffiStatus);
        private static readonly OnDisconnectedFn OnDisconnectedDelegate = OnDisconnected;
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void OnDisconnectedProxyFn(ulong handle, out FfiStatus __boltffiStatus);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate void OnDataReceivedFn(ulong handle, IntPtr @interface, UIntPtr interfaceLen, IntPtr path, UIntPtr pathLen, IntPtr data, UIntPtr dataLen, out FfiStatus __boltffiStatus);
        private static readonly OnDataReceivedFn OnDataReceivedDelegate = OnDataReceived;
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void OnDataReceivedProxyFn(ulong handle, IntPtr @interface, UIntPtr interfaceLen, IntPtr path, UIntPtr pathLen, IntPtr data, UIntPtr dataLen, out FfiStatus __boltffiStatus);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate void OnObjectReceivedFn(ulong handle, IntPtr @interface, UIntPtr interfaceLen, IntPtr path, UIntPtr pathLen, IntPtr entries, UIntPtr entriesLen, out FfiStatus __boltffiStatus);
        private static readonly OnObjectReceivedFn OnObjectReceivedDelegate = OnObjectReceived;
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void OnObjectReceivedProxyFn(ulong handle, IntPtr @interface, UIntPtr interfaceLen, IntPtr path, UIntPtr pathLen, IntPtr entries, UIntPtr entriesLen, out FfiStatus __boltffiStatus);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate void OnPropertyReceivedFn(ulong handle, IntPtr @interface, UIntPtr interfaceLen, IntPtr path, UIntPtr pathLen, IntPtr data, UIntPtr dataLen, out FfiStatus __boltffiStatus);
        private static readonly OnPropertyReceivedFn OnPropertyReceivedDelegate = OnPropertyReceived;
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void OnPropertyReceivedProxyFn(ulong handle, IntPtr @interface, UIntPtr interfaceLen, IntPtr path, UIntPtr pathLen, IntPtr data, UIntPtr dataLen, out FfiStatus __boltffiStatus);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        private delegate void OnPropertyUnsetFn(ulong handle, IntPtr @interface, UIntPtr interfaceLen, IntPtr path, UIntPtr pathLen, out FfiStatus __boltffiStatus);
        private static readonly OnPropertyUnsetFn OnPropertyUnsetDelegate = OnPropertyUnset;
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void OnPropertyUnsetProxyFn(ulong handle, IntPtr @interface, UIntPtr interfaceLen, IntPtr path, UIntPtr pathLen, out FfiStatus __boltffiStatus);

        [DllImport(NativeMethods.LibName, EntryPoint = "boltffi_register_event_listener_vtable")]
        private static extern void RegisterNative(IntPtr vtable);

        [DllImport(NativeMethods.LibName, EntryPoint = "boltffi_create_event_listener_handle")]
        private static extern BoltFFICallbackHandle CreateNative(ulong handle);
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct FfiStatus
    {
        public int code;
    }


    [StructLayout(LayoutKind.Sequential)]
    internal struct FfiBuf
    {
        public IntPtr ptr;
        public UIntPtr len;
        public UIntPtr cap;
        public UIntPtr align;

        internal static unsafe FfiBuf FromBytes(byte[] bytes)
        {
            if (bytes.Length == 0)
            {
                return default;
            }

            void* allocated = NativeMemory.Alloc((nuint)bytes.Length);
            Marshal.Copy(bytes, 0, (IntPtr)allocated, bytes.Length);
            return new FfiBuf
            {
                ptr = (IntPtr)allocated,
                len = (UIntPtr)bytes.Length,
                cap = (UIntPtr)bytes.Length,
                align = (UIntPtr)1,
            };
        }
    }


    internal sealed class WireReader
    {
        // Reads directly from the unmanaged FfiBuf pointer — no eager copy into
        // a managed byte[]. Safe APIs only: Marshal.Read* for primitives,
        // Marshal.PtrToStringUTF8 for length-prefixed UTF-8, Marshal.Copy for
        // bytes. BitConverter.IsLittleEndian is a JIT intrinsic that folds the
        // byte-swap branch away on little-endian hosts (all our supported
        // targets).
        private readonly IntPtr _ptr;
        private readonly int _length;
        private int _pos;

        internal WireReader(FfiBuf buf)
        {
            _ptr = buf.ptr;
            _length = buf.ptr == IntPtr.Zero ? 0 : checked((int)(nuint)buf.len);
            _pos = 0;
        }

        internal WireReader(IntPtr ptr, UIntPtr len)
        {
            _ptr = ptr;
            _length = ptr == IntPtr.Zero ? 0 : checked((int)(nuint)len);
            _pos = 0;
        }

        internal bool ReadBool() => ReadU8() != 0;

        internal sbyte ReadI8()
        {
            Require(1, "i8");
            sbyte v = (sbyte)Marshal.ReadByte(_ptr, _pos);
            _pos += 1;
            return v;
        }

        internal byte ReadU8()
        {
            Require(1, "u8");
            byte v = Marshal.ReadByte(_ptr, _pos);
            _pos += 1;
            return v;
        }

        internal short ReadI16()
        {
            Require(2, "i16");
            short v = Marshal.ReadInt16(_ptr, _pos);
            _pos += 2;
            return BitConverter.IsLittleEndian ? v : BinaryPrimitives.ReverseEndianness(v);
        }

        internal ushort ReadU16()
        {
            Require(2, "u16");
            ushort v = (ushort)Marshal.ReadInt16(_ptr, _pos);
            _pos += 2;
            return BitConverter.IsLittleEndian ? v : BinaryPrimitives.ReverseEndianness(v);
        }

        internal int ReadI32()
        {
            Require(4, "i32");
            int v = Marshal.ReadInt32(_ptr, _pos);
            _pos += 4;
            return BitConverter.IsLittleEndian ? v : BinaryPrimitives.ReverseEndianness(v);
        }

        internal uint ReadU32()
        {
            Require(4, "u32");
            uint v = (uint)Marshal.ReadInt32(_ptr, _pos);
            _pos += 4;
            return BitConverter.IsLittleEndian ? v : BinaryPrimitives.ReverseEndianness(v);
        }

        internal long ReadI64()
        {
            Require(8, "i64");
            long v = Marshal.ReadInt64(_ptr, _pos);
            _pos += 8;
            return BitConverter.IsLittleEndian ? v : BinaryPrimitives.ReverseEndianness(v);
        }

        internal ulong ReadU64()
        {
            Require(8, "u64");
            ulong v = (ulong)Marshal.ReadInt64(_ptr, _pos);
            _pos += 8;
            return BitConverter.IsLittleEndian ? v : BinaryPrimitives.ReverseEndianness(v);
        }

        internal float ReadF32()
        {
            Require(4, "f32");
            int bits = Marshal.ReadInt32(_ptr, _pos);
            _pos += 4;
            return BitConverter.Int32BitsToSingle(BitConverter.IsLittleEndian ? bits : BinaryPrimitives.ReverseEndianness(bits));
        }

        internal double ReadF64()
        {
            Require(8, "f64");
            long bits = Marshal.ReadInt64(_ptr, _pos);
            _pos += 8;
            return BitConverter.Int64BitsToDouble(BitConverter.IsLittleEndian ? bits : BinaryPrimitives.ReverseEndianness(bits));
        }

        // usize/isize travel as 64-bit integers on the wire so the wire
        // layout stays stable across pointer widths.
        internal nint ReadNInt() => (nint)ReadI64();
        internal nuint ReadNUInt() => (nuint)ReadU64();

        internal string ReadString()
        {
            int len = ReadI32();
            if (len == 0) return "";
            if (len < 0) throw new InvalidOperationException("corrupt wire: negative string length");
            Require(len, "string payload");
            string v = Marshal.PtrToStringUTF8(_ptr + _pos, len)
                ?? throw new InvalidOperationException("PtrToStringUTF8 returned null");
            _pos += len;
            return v;
        }

        internal byte[] ReadBytes()
        {
            int len = ReadI32();
            if (len == 0) return Array.Empty<byte>();
            if (len < 0) throw new InvalidOperationException("corrupt wire: negative bytes length");
            Require(len, "bytes payload");
            byte[] v = new byte[len];
            Marshal.Copy(_ptr + _pos, v, 0, len);
            _pos += len;
            return v;
        }

        /// Reads the remaining bytes of this buffer as a `T[]`, assuming
        /// the buffer holds a raw element array with no length prefix.
        /// This matches the wire shape of a top-level `Vec<T>` return,
        /// where the FfiBuf's own `len` provides the element count.
        internal T[] ReadBlittableArray<T>() where T : unmanaged
        {
            int byteCount = _length - _pos;
            if (byteCount < 0)
                throw new InvalidOperationException("corrupt wire: read position past end");
            int elementSize = Unsafe.SizeOf<T>();
            if (byteCount % elementSize != 0)
                throw new InvalidOperationException(
                    "corrupt wire: blittable array byte count is not a multiple of element size");
            if (byteCount == 0) return Array.Empty<T>();
            int count = byteCount / elementSize;
            T[] result = new T[count];
            // Fast path via Marshal.Copy's per-type overloads for the types
            // that ship with one (byte, short, int, long, float, double).
            // Unsigned primitives and any other unmanaged T fall through to
            // a byte scratch buffer reinterpreted via MemoryMarshal.AsBytes.
            // Little-endian hosts only; big-endian would need byte-swap.
            switch (result)
            {
                case byte[] dst:
                    Marshal.Copy(_ptr + _pos, dst, 0, byteCount);
                    break;
                case short[] dst:
                    Marshal.Copy(_ptr + _pos, dst, 0, count);
                    break;
                case int[] dst:
                    Marshal.Copy(_ptr + _pos, dst, 0, count);
                    break;
                case long[] dst:
                    Marshal.Copy(_ptr + _pos, dst, 0, count);
                    break;
                case float[] dst:
                    Marshal.Copy(_ptr + _pos, dst, 0, count);
                    break;
                case double[] dst:
                    Marshal.Copy(_ptr + _pos, dst, 0, count);
                    break;
                default:
                    byte[] scratch = new byte[byteCount];
                    Marshal.Copy(_ptr + _pos, scratch, 0, byteCount);
                    scratch.AsSpan().CopyTo(MemoryMarshal.AsBytes(result.AsSpan()));
                    break;
            }
            _pos += byteCount;
            return result;
        }

        internal bool[] ReadBoolArray()
        {
            int count = _length - _pos;
            if (count < 0)
                throw new InvalidOperationException("corrupt wire: read position past end");
            if (count == 0) return Array.Empty<bool>();
            bool[] result = new bool[count];
            for (int i = 0; i < count; i++)
            {
                result[i] = Marshal.ReadByte(_ptr, _pos + i) != 0;
            }
            _pos += count;
            return result;
        }

        internal nint[] ReadNIntArray()
        {
            long[] raw = ReadBlittableArray<long>();
            nint[] result = new nint[raw.Length];
            for (int i = 0; i < raw.Length; i++) result[i] = (nint)raw[i];
            return result;
        }

        internal nuint[] ReadNUIntArray()
        {
            long[] raw = ReadBlittableArray<long>();
            nuint[] result = new nuint[raw.Length];
            for (int i = 0; i < raw.Length; i++) result[i] = (nuint)(ulong)raw[i];
            return result;
        }

        /// Reads a length-prefixed `T[]` whose bytes follow the 4-byte count.
        /// Used for `Vec<T>` nested inside an encoded outer container, where
        /// the outer codec needs an explicit count to know how far to advance
        /// the cursor between sibling elements.
        internal T[] ReadLengthPrefixedBlittableArray<T>() where T : unmanaged
        {
            int count = ReadI32();
            if (count < 0) throw new InvalidOperationException("corrupt wire: negative array length");
            if (count == 0) return Array.Empty<T>();
            int elementSize = Unsafe.SizeOf<T>();
            int byteCount = checked(count * elementSize);
            Require(byteCount, "blittable array payload");
            T[] result = new T[count];
            switch (result)
            {
                case byte[] dst:
                    Marshal.Copy(_ptr + _pos, dst, 0, byteCount);
                    break;
                case short[] dst:
                    Marshal.Copy(_ptr + _pos, dst, 0, count);
                    break;
                case int[] dst:
                    Marshal.Copy(_ptr + _pos, dst, 0, count);
                    break;
                case long[] dst:
                    Marshal.Copy(_ptr + _pos, dst, 0, count);
                    break;
                case float[] dst:
                    Marshal.Copy(_ptr + _pos, dst, 0, count);
                    break;
                case double[] dst:
                    Marshal.Copy(_ptr + _pos, dst, 0, count);
                    break;
                default:
                    byte[] scratch = new byte[byteCount];
                    Marshal.Copy(_ptr + _pos, scratch, 0, byteCount);
                    scratch.AsSpan().CopyTo(MemoryMarshal.AsBytes(result.AsSpan()));
                    break;
            }
            _pos += byteCount;
            return result;
        }

        internal bool[] ReadLengthPrefixedBoolArray()
        {
            int count = ReadI32();
            if (count < 0) throw new InvalidOperationException("corrupt wire: negative array length");
            if (count == 0) return Array.Empty<bool>();
            Require(count, "bool array payload");
            bool[] result = new bool[count];
            for (int i = 0; i < count; i++)
            {
                result[i] = Marshal.ReadByte(_ptr, _pos + i) != 0;
            }
            _pos += count;
            return result;
        }

        internal nint[] ReadLengthPrefixedNIntArray()
        {
            long[] raw = ReadLengthPrefixedBlittableArray<long>();
            nint[] result = new nint[raw.Length];
            for (int i = 0; i < raw.Length; i++) result[i] = (nint)raw[i];
            return result;
        }

        internal nuint[] ReadLengthPrefixedNUIntArray()
        {
            long[] raw = ReadLengthPrefixedBlittableArray<long>();
            nuint[] result = new nuint[raw.Length];
            for (int i = 0; i < raw.Length; i++) result[i] = (nuint)(ulong)raw[i];
            return result;
        }

        /// Reads a length-prefixed array whose elements are decoded by
        /// invoking `read` once per slot. Used for `Vec<T>` where each
        /// element has variable wire width (strings, nested encoded vecs,
        /// records).
        internal T[] ReadEncodedArray<T>(Func<WireReader, T> read)
        {
            int count = ReadI32();
            if (count < 0) throw new InvalidOperationException("corrupt wire: negative array length");
            if (count == 0) return Array.Empty<T>();
            T[] result = new T[count];
            for (int i = 0; i < count; i++)
            {
                result[i] = read(this);
            }
            return result;
        }

        private void Require(int n, string kind)
        {
            if (n < 0 || n > _length - _pos) throw new InvalidOperationException("corrupt wire: truncated " + kind);
        }
    }


    internal sealed class WireWriter : IDisposable
    {
        private const int MinCapacity = 16;

        private byte[] _buffer;
        private int _pos;
        private bool _disposed;

        internal WireWriter(int initialCapacity)
        {
            int cap = Math.Max(initialCapacity, MinCapacity);
            _buffer = ArrayPool<byte>.Shared.Rent(cap);
            _pos = 0;
            _disposed = false;
        }

        /// <summary>Copy the written bytes into a fresh managed array.</summary>
        internal byte[] ToArray()
        {
            if (_pos == 0) return Array.Empty<byte>();
            byte[] result = new byte[_pos];
            Buffer.BlockCopy(_buffer, 0, result, 0, _pos);
            return result;
        }

        internal int Position => _pos;

        internal void WriteBool(bool v) { EnsureCapacity(1); _buffer[_pos++] = (byte)(v ? 1 : 0); }
        internal void WriteI8(sbyte v) { EnsureCapacity(1); _buffer[_pos++] = (byte)v; }
        internal void WriteU8(byte v) { EnsureCapacity(1); _buffer[_pos++] = v; }
        internal void WriteI16(short v) { EnsureCapacity(2); BinaryPrimitives.WriteInt16LittleEndian(_buffer.AsSpan(_pos), v); _pos += 2; }
        internal void WriteU16(ushort v) { EnsureCapacity(2); BinaryPrimitives.WriteUInt16LittleEndian(_buffer.AsSpan(_pos), v); _pos += 2; }
        internal void WriteI32(int v) { EnsureCapacity(4); BinaryPrimitives.WriteInt32LittleEndian(_buffer.AsSpan(_pos), v); _pos += 4; }
        internal void WriteU32(uint v) { EnsureCapacity(4); BinaryPrimitives.WriteUInt32LittleEndian(_buffer.AsSpan(_pos), v); _pos += 4; }
        internal void WriteI64(long v) { EnsureCapacity(8); BinaryPrimitives.WriteInt64LittleEndian(_buffer.AsSpan(_pos), v); _pos += 8; }
        internal void WriteU64(ulong v) { EnsureCapacity(8); BinaryPrimitives.WriteUInt64LittleEndian(_buffer.AsSpan(_pos), v); _pos += 8; }
        internal void WriteF32(float v) { EnsureCapacity(4); BinaryPrimitives.WriteSingleLittleEndian(_buffer.AsSpan(_pos), v); _pos += 4; }
        internal void WriteF64(double v) { EnsureCapacity(8); BinaryPrimitives.WriteDoubleLittleEndian(_buffer.AsSpan(_pos), v); _pos += 8; }

        internal void WriteNInt(nint v) => WriteI64((long)v);
        internal void WriteNUInt(nuint v) => WriteU64((ulong)v);

        internal void WriteString(string v)
        {
            int byteCount = Encoding.UTF8.GetByteCount(v);
            WriteI32(byteCount);
            if (byteCount == 0) return;
            EnsureCapacity(byteCount);
            Encoding.UTF8.GetBytes(v, 0, v.Length, _buffer, _pos);
            _pos += byteCount;
        }

        internal void WriteBytes(byte[] v)
        {
            WriteI32(v.Length);
            if (v.Length == 0) return;
            EnsureCapacity(v.Length);
            Buffer.BlockCopy(v, 0, _buffer, _pos, v.Length);
            _pos += v.Length;
        }

        internal void WriteBlittableArray<T>(T[] v) where T : unmanaged
        {
            WriteI32(v.Length);
            if (v.Length == 0) return;
            int byteCount = checked(v.Length * Unsafe.SizeOf<T>());
            EnsureCapacity(byteCount);
            // Reinterpret the source T[] as bytes and block-copy into the
            // managed buffer. Zero extra allocations, one copy. Little-endian
            // hosts only; big-endian would need byte-swap.
            MemoryMarshal.AsBytes(v.AsSpan()).CopyTo(_buffer.AsSpan(_pos, byteCount));
            _pos += byteCount;
        }

        internal void WriteBoolArray(bool[] v)
        {
            WriteI32(v.Length);
            if (v.Length == 0) return;
            EnsureCapacity(v.Length);
            for (int i = 0; i < v.Length; i++)
            {
                _buffer[_pos + i] = (byte)(v[i] ? 1 : 0);
            }
            _pos += v.Length;
        }

        internal void WriteNIntArray(nint[] v)
        {
            long[] widened = new long[v.Length];
            for (int i = 0; i < v.Length; i++) widened[i] = (long)v[i];
            WriteBlittableArray(widened);
        }

        internal void WriteNUIntArray(nuint[] v)
        {
            long[] widened = new long[v.Length];
            for (int i = 0; i < v.Length; i++) widened[i] = (long)(ulong)v[i];
            WriteBlittableArray(widened);
        }

        /// Byte size of an encoded `T[]`: the `sizeof(int)` length prefix
        /// plus the per-element size. Size expressions for `Vec<T>` with
        /// variable-width elements (strings, nested vecs, records) use this
        /// helper to drive the `WireWriter` pre-size so its initial
        /// capacity matches the payload and no growth copy is needed.
        internal static int EncodedArraySize<T>(T[] v, Func<T, int> sizer)
        {
            int total = sizeof(int);
            for (int i = 0; i < v.Length; i++) total += sizer(v[i]);
            return total;
        }

        private void EnsureCapacity(int additional)
        {
            if (_pos + additional <= _buffer.Length) return;
            int next = Math.Max(_buffer.Length * 2, _pos + additional);
            byte[] grown = ArrayPool<byte>.Shared.Rent(next);
            Buffer.BlockCopy(_buffer, 0, grown, 0, _pos);
            ArrayPool<byte>.Shared.Return(_buffer);
            _buffer = grown;
        }

        public void Dispose()
        {
            if (_disposed) return;
            _disposed = true;
            ArrayPool<byte>.Shared.Return(_buffer);
            _buffer = Array.Empty<byte>();
        }
    }


    [StructLayout(LayoutKind.Sequential)]
    internal struct BoltFFICallbackHandle
    {
        public ulong handle;
        public IntPtr vtable;

        internal static BoltFFICallbackHandle Null => default;
        internal bool IsNull => handle == 0 || vtable == IntPtr.Zero;
    }

    internal readonly struct BoltFFIUnit
    {
    }

    internal readonly struct BoltFFIResult<TOk, TErr>
    {
        private readonly TOk _okValue;
        private readonly TErr _errValue;

        private BoltFFIResult(TOk okValue, TErr errValue, bool isOk)
        {
            _okValue = okValue;
            _errValue = errValue;
            IsOk = isOk;
        }

        internal bool IsOk { get; }
        internal TOk OkValue => _okValue;
        internal TErr ErrValue => _errValue;

        internal static BoltFFIResult<TOk, TErr> Ok(TOk value) => new(value, default!, true);
        internal static BoltFFIResult<TOk, TErr> Err(TErr value) => new(default!, value, false);
    }

    internal static class BoltFFICallbackReturn
    {
        internal static unsafe void Store(byte[] bytes, out IntPtr outPtr, out UIntPtr outLen)
        {
            if (bytes.Length == 0)
            {
                outPtr = IntPtr.Zero;
                outLen = UIntPtr.Zero;
                return;
            }

            void* allocated = NativeMemory.Alloc((nuint)bytes.Length);
            Marshal.Copy(bytes, 0, (IntPtr)allocated, bytes.Length);
            outPtr = (IntPtr)allocated;
            outLen = (UIntPtr)bytes.Length;
        }

        internal static unsafe void Free(IntPtr ptr)
        {
            if (ptr != IntPtr.Zero)
            {
                NativeMemory.Free((void*)ptr);
            }
        }
    }


    internal static class NativeMethods
    {
        internal const string LibName = "astarte_device_sdk_bindings";

        [DllImport(LibName, EntryPoint = "boltffi_free_buf")]
        internal static extern void FreeBuf(FfiBuf buf);

        [DllImport(LibName, EntryPoint = "boltffi_astarte_device_new")]
        internal static extern IntPtr AstarteDeviceNew(byte[] config, UIntPtr configLen, byte[] interfacesDir, UIntPtr interfacesDirLen);

        [DllImport(LibName, EntryPoint = "boltffi_astarte_device_free")]
        internal static extern void AstarteDeviceFree(IntPtr handle);
        [DllImport(LibName, EntryPoint = "boltffi_astarte_device_send")]
        internal static extern void AstarteDeviceSend(IntPtr self, byte[] interfaceName, UIntPtr interfaceNameLen, byte[] interfacePath, UIntPtr interfacePathLen, byte[] data, UIntPtr dataLen);
        [DllImport(LibName, EntryPoint = "boltffi_astarte_device_start_listening")]
        internal static extern void AstarteDeviceStartListening(IntPtr self, BoltFFICallbackHandle listener);
        [DllImport(LibName, EntryPoint = "boltffi_astarte_device_disconenct")]
        internal static extern void AstarteDeviceDisconenct(IntPtr self);
    }
}
