// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System;
using System.Text;

namespace AstarteDeviceSdkBindings
{
    /// <summary>
    /// One field of an Object-aggregation event (key + converted value).
    /// </summary>
    public readonly record struct ObjectEntry(
        string Key,
        AstarteVal Value
    )
    {
        internal static ObjectEntry Decode(WireReader reader) =>
            new ObjectEntry(
                reader.ReadString(),
                AstarteVal.Decode(reader)
            );

        internal int WireEncodedSize() =>
            (4 + Encoding.UTF8.GetByteCount(this.Key)) +
            this.Value.WireEncodedSize();

        internal void WireEncodeTo(WireWriter wire)
        {
            wire.WriteString(this.Key);
            this.Value.WireEncodeTo(wire);
        }
    }
}