// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System;
using System.Text;

namespace AstarteDeviceSdkBindings
{
    /// <summary>
    /// A single key–value field within an Astarte Object-aggregation event.
    /// A list of these is delivered to <see cref="EventListener.OnObjectReceived"/>.
    /// </summary>
    /// <param name="Key">The endpoint name of the field (e.g. <c>"temperature"</c>).</param>
    /// <param name="Value">The field value as an <see cref="AstarteVal"/> variant.</param>
    public readonly record struct ObjectEntry(
        string Key,
        AstarteVal Value
    )
    {
        internal static ObjectEntry Decode(WireReader reader) =>
            new ObjectEntry(
                reader.ReadString(),
                AstarteVal.Decode(reader)
            );

        internal int WireEncodedSize() =>
            (4 + Encoding.UTF8.GetByteCount(this.Key)) +
            this.Value.WireEncodedSize();

        internal void WireEncodeTo(WireWriter wire)
        {
            wire.WriteString(this.Key);
            this.Value.WireEncodeTo(wire);
        }
    }
}