// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System;
using System.Text;

namespace AstarteDeviceSdkBindings
{
    public abstract record SdkError
    {
        private SdkError() { }
        public sealed record Config(
            string Msg
        ) : SdkError;
        public sealed record Connection(
            string Msg
        ) : SdkError;
        public sealed record Send(
            string Msg
        ) : SdkError;

        internal static SdkError Decode(WireReader reader) =>
            reader.ReadI32() switch
            {
                0 => new Config(
                    reader.ReadString()
                ),
                1 => new Connection(
                    reader.ReadString()
                ),
                2 => new Send(
                    reader.ReadString()
                ),
                int tag => throw new InvalidOperationException($"Unknown SdkError tag: {tag}"),
            };

        internal int WireEncodedSize() => 4 + this switch
        {
            Config _v => (4 + Encoding.UTF8.GetByteCount(_v.Msg)),
            Connection _v => (4 + Encoding.UTF8.GetByteCount(_v.Msg)),
            Send _v => (4 + Encoding.UTF8.GetByteCount(_v.Msg)),
            _ => throw new InvalidOperationException($"Unknown SdkError variant"),
        };

        internal void WireEncodeTo(WireWriter wire)
        {
            switch (this)
            {
                case Config _v:
                    wire.WriteI32(0);
                    wire.WriteString(_v.Msg);
                    break;
                case Connection _v:
                    wire.WriteI32(1);
                    wire.WriteString(_v.Msg);
                    break;
                case Send _v:
                    wire.WriteI32(2);
                    wire.WriteString(_v.Msg);
                    break;
            }
        }
    }
    /// <summary>
    /// Thrown by generated wrapper methods when the Rust side returns
    /// a <c>SdkError</c> as the error. The original value is
    /// exposed through <c>Error</c>; the inherited <c>Message</c>
    /// derives from it (forwarded from a <c>Message</c> field when the
    /// wrapped type has one, otherwise the value's <c>ToString()</c>).
    /// </summary>
    public sealed class SdkErrorException : Exception
    {
        public SdkError Error { get; }

        public SdkErrorException(SdkError error) : base(error.ToString())
        {
            Error = error;
        }
    }
}