// <auto-generated>
// This file was generated by BoltFFI. Do not edit.
// </auto-generated>
#nullable enable

using System;
using System.Text;

namespace AstarteDeviceSdkBindings
{
    /// <summary>
    /// Discriminated union of errors that the Astarte Device SDK can return.
    /// Use pattern matching to distinguish between error kinds.
    /// </summary>
    public abstract record SdkError
    {
        private SdkError() { }

        /// <summary>
        /// A configuration or initialisation error (invalid credentials, malformed pairing URL,
        /// missing interface files, etc.).
        /// </summary>
        /// <param name="Msg">Human-readable description from the Rust SDK.</param>
        public sealed record Config(
            string Msg
        ) : SdkError;

        /// <summary>
        /// A connection error (broker unreachable, TLS handshake failure, authentication
        /// rejected, etc.).
        /// </summary>
        /// <param name="Msg">Human-readable description from the Rust SDK.</param>
        public sealed record Connection(
            string Msg
        ) : SdkError;

        /// <summary>An error that occurred while publishing data to the broker.</summary>
        /// <param name="Msg">Human-readable description from the Rust SDK.</param>
        public sealed record Send(
            string Msg
        ) : SdkError;

        internal static SdkError Decode(WireReader reader) =>
            reader.ReadI32() switch
            {
                0 => new Config(
                    reader.ReadString()
                ),
                1 => new Connection(
                    reader.ReadString()
                ),
                2 => new Send(
                    reader.ReadString()
                ),
                int tag => throw new InvalidOperationException($"Unknown SdkError tag: {tag}"),
            };

        internal int WireEncodedSize() => 4 + this switch
        {
            Config _v => (4 + Encoding.UTF8.GetByteCount(_v.Msg)),
            Connection _v => (4 + Encoding.UTF8.GetByteCount(_v.Msg)),
            Send _v => (4 + Encoding.UTF8.GetByteCount(_v.Msg)),
            _ => throw new InvalidOperationException($"Unknown SdkError variant"),
        };

        internal void WireEncodeTo(WireWriter wire)
        {
            switch (this)
            {
                case Config _v:
                    wire.WriteI32(0);
                    wire.WriteString(_v.Msg);
                    break;
                case Connection _v:
                    wire.WriteI32(1);
                    wire.WriteString(_v.Msg);
                    break;
                case Send _v:
                    wire.WriteI32(2);
                    wire.WriteString(_v.Msg);
                    break;
            }
        }
    }
    /// <summary>
    /// Exception thrown when the Rust SDK returns an <see cref="SdkError"/>.
    /// The structured error value is available via <see cref="Error"/>;
    /// <see cref="Exception.Message"/> is derived from it.
    /// </summary>
    public sealed class SdkErrorException : Exception
    {
        /// <summary>The structured SDK error that caused this exception.</summary>
        public SdkError Error { get; }

        public SdkErrorException(SdkError error) : base(error.ToString())
        {
            Error = error;
        }
    }
}