"""Astarte Device SDK Python Bindings."""

from astarte.device.config import DeviceConfig
from astarte.device.data import (
    CDataRefs,
    DeviceBinaryBlob,
    DeviceData,
    DeviceDataBinaryBlob,
    DeviceDataBinaryBlobArray,
    DeviceDataBoolean,
    DeviceDataBooleanArray,
    DeviceDataDateTime,
    DeviceDataDateTimeArray,
    DeviceDataDouble,
    DeviceDataDoubleArray,
    DeviceDataInteger,
    DeviceDataIntegerArray,
    DeviceDataLongInteger,
    DeviceDataLongIntegerArray,
    DeviceDataScalarType,
    DeviceDataString,
    DeviceDataStringArray,
    DeviceDataVectorType,
    DeviceEvent,
    DeviceObject,
    DeviceProperty,
    DeviceValue,
    DeviceValueIndividual,
    DeviceValueObject,
    DeviceValuePropertySet,
    DeviceValuePropertyUnset,
)
from astarte.device.device import Device
from astarte.device.exceptions import (
    AstarteError,
    ConnectError,
    DisconnectError,
    GetPropertyError,
    HandleEventsError,
    InvalidNativeValueError,
    ReceiveError,
    SendError,
)

__all__ = [
    # Core Client & Config
    "Device",
    "DeviceConfig",
    # Data & Values
    "CDataRefs",
    "DeviceBinaryBlob",
    "DeviceData",
    "DeviceDataDouble",
    "DeviceDataInteger",
    "DeviceDataBoolean",
    "DeviceDataLongInteger",
    "DeviceDataString",
    "DeviceDataBinaryBlob",
    "DeviceDataDateTime",
    "DeviceDataDoubleArray",
    "DeviceDataIntegerArray",
    "DeviceDataBooleanArray",
    "DeviceDataLongIntegerArray",
    "DeviceDataStringArray",
    "DeviceDataBinaryBlobArray",
    "DeviceDataDateTimeArray",
    "DeviceDataScalarType",
    "DeviceDataVectorType",
    "DeviceObject",
    "DeviceValue",
    "DeviceValueIndividual",
    "DeviceValueObject",
    "DeviceValuePropertySet",
    "DeviceValuePropertyUnset",
    "DeviceProperty",
    "DeviceEvent",
    # Exceptions
    "AstarteError",
    "InvalidNativeValueError",
    "GetPropertyError",
    "SendError",
    "ReceiveError",
    "DisconnectError",
    "ConnectError",
    "HandleEventsError",
]
